YosysHQ/nextpnr

gui/treemodel.h
This fixes mysterious crashes when a new context was being loaded. The
'Bels', 'Wires', and 'Nets' roots would get replaced by new ones in
TreeModel::Model::loadContext, but they would not get unregistered from
their parent.
=> gui: treemodel: unregister from parent when we get destroyed

gui/treemodel.cc
Tree update was failing due to improper removal of element from a unordered_map
=> Properly delete element from unordered_map

README.md, ecp5/arch.cc, ecp5/arch.h, ecp5/bitstream.cc, ecp5/bitstream.h, ecp5/config.cc, ecp5/config.h, ecp5/family.cmake, ecp5/main.cc, ecp5/synth/.gitignore, ecp5/trellis_import.py
In order to avoid C++ link problems of various kinds, we don't use libtrellis for bitstream gen any more, but just write a text config file that can be packed to a bitstream with ecppack, like the current ice40 flow.
=> Remove libtrellis link for bitstream gen

ice40/arch.cc, ice40/arch.h, ice40/chipdb.py
Import the cell delays into the database and use them instead of approximate values. Currently this imports propagation delays, but not setup/hold times yet - these still need to be done.
This should give much more accurate timing estimates on the "slow" parts like the UP5K (cc @whitequark)
=> ice40: Use real cell timings

ecp5/trellis_import.py
Accidentally relied on Python dictionary ordering, which happened to work on some distros but not on others. This explicitly orders correctly instead and should fix all these issues.
=> ecp5: Write tiletype names in correct order

gui/application.cc
Windows build at least needs proper handling of CTRL-C in order to correctly close application
=> Handle CTRL-C for windows build

common/placer1.cc, common/timing.cc, ice40/main.cc
During my experimentation with slack redistribution, I inadvertently juggled around where the first `assign_budget` is called for ice40 from after packing (where there are no net delays) to after initial placement (where a net delay estimate exists). 
This effect would cause the port budget to be initialised according to estimate net delays based on the (poor) initial placement, even when slack redistribution is not enabled.
This PR reverts this behaviour.
=> Restore original assign_budget behaviour (to distribute slack evenly)

common/placer1.cc, common/timing.cc, docs/archapi.md, ecp5/arch.cc, ecp5/arch.h, generic/arch.cc, generic/arch.h, ice40/arch.cc, ice40/arch.h, ice40/main.cc
It appears that `Arch::getBudgetOverride()` wasn't being used correctly during STA. Builds on #38.
Also changed signature of `Arch::getBudgetOverride()` to `bool Arch::getBudgetOverride(const Netinfo*, const PortRef&, delay_t&)` to modify budget in place and return bool if this was done.
This appears to return a small QoR improvement:
On #38:
```
  | min | avg | max | success (/32)
master 100MHz | 50.88 | 55.04 | 60.28 | 32
master 70MHz | 50.4 | 54.97 | 59.13 | 31
master 60MHz | 51.16 | 54.97 | 59.06 | 32
master (default=12MHz) | 51.54 | 54.42 | 59.73 | 32
```
This:
```
  | min | avg | max | success (/32)
master 100MHz | 49.87 | 55.45 | 61 | 32
master 70MHz | 51.14 | 55.94 | 63.33 | 32
master 60MHz | 51.71 | 57.32 | 62.53 | 32
master (default=12MHz) | 50.17 | 56.25 | 62.26 | 31
```
=> Fix budget overrides

common/timing.cc
```
Info: Slack histogram:
Info:  legend: * represents 54 endpoint(s)
Info:          + represents [1,54) endpoint(s)
Info: [ -2748,  -1953) |+
Info: [ -1953,  -1158) |+
Info: [ -1158,   -363) |*+
Info: [  -363,    432) |**+
Info: [   432,   1227) |***+
Info: [  1227,   2022) |*****+
Info: [  2022,   2817) |********+
Info: [  2817,   3612) |**************+
Info: [  3612,   4407) |**************************+
Info: [  4407,   5202) |**********************************+
Info: [  5202,   5997) |**************************************************+
Info: [  5997,   6792) |************************************************************ 
Info: [  6792,   7587) |**********************************************************+
Info: [  7587,   8382) |************************************************+
Info: [ …
```
=> Improve slack histogram clarity

ice40/cells.cc, ice40/pack.cc
- Fix the SDO port definition on the iCE40 PLL packed cell.
- Warn instead of crashing when the user design contains a port that is not present in the PLL packed cell.
- Style fixes in PLL packing logging.
Fixes #55 .
=> ice40: make PLL packing more robust

gui/fpgaviewwidget.cc
Turns out the bounding box of the quadtree root wasn't large enough to accommodate elements that were on the edge of the bounding box. Any time we added lines, we would slightly enlarge their bounding boxes, and thus exceed the root bounding box size.
This would fail silently - we also add an assert against this to easier debug similar bugs in the future.
=> gui: fix #57

common/chain_utils.h, common/design_utils.cc, common/design_utils.h, ecp5/arch_place.cc, ecp5/archdefs.h, ecp5/bitstream.cc, ecp5/cells.cc, ecp5/cells.h, ecp5/pack.cc, ice40/chains.cc
This adds carry support for ECP5 to the packer and bitstream gen (using relative placement constraints). Tested with a few examples including picorv32.
=> Adding ECP5 carry support

common/design_utils.cc, common/design_utils.h, common/nextpnr.cc, common/timing.cc, ecp5/arch.cc, ecp5/bitstream.cc, ecp5/cells.cc, ecp5/cells.h, ecp5/globals.cc, ecp5/pack.cc
Tested with picorv32 and a few other small tests. Also includes a fix for flipflop packing in general. 
Need still to investigate why the WCK -> F0/F1 timing arc (i.e. write clock to output) causes problems with the topological ordering.
=> Adding support for ECP5 distributed RAM

common/command.cc, common/command.h
This implements the following changes:
- `--run` now runs a Python script replacing the default flow (previously this ran the script at the end of the flow)
- New options `--pre-pack`, `--pre-place`, `--pre-route`, and --`post-route` allow running Python scripts at a specific point in the default flow, while still running the default flow normally. This will allow Python scripts to be used as a way of implementing constraints.
=> Allow running Python scripts for all points in flow

common/nextpnr.h, gui/fpgaviewwidget.cc, gui/fpgaviewwidget.h, gui/lineshader.cc, gui/lineshader.h
Profiling revealed that memcpy() in QOpenGLBuffer::allocate() had been taking
the most time during paintGL() calls. I've been able to take the CPU usage
down to about 1/4 of its previous values by caching elements in VBOs and
updating them only after subsequent calls to renderGraphicElement().
Signed-off-by: Mateusz Zalega <mateusz@appliedsourcery.com>
=> gui: improved FPGAViewWidget::paintGL() performance

gui/designwidget.cc, gui/designwidget.h, gui/fpgaviewwidget.cc, gui/fpgaviewwidget.h, gui/quadtree.h, gui/treemodel.cc, gui/treemodel.h, ice40/arch.h
- make grid only cover device itself
- fix for ice40 grid dimensions
- split device tree to multiple tabs/trees
- made bel tree available on all arch, since it use standard api
=> Gui changes

ice40/bitstream.cc
=> ice40: Don't set colbuf bits for 384

json/jsonparse.cc
no missing.json file present
before
```
nextpnr-ice40 --lp384 --json missing.json --pcf constraints.pcf --asc fine.asc
ERROR: Unexpected EOF in JSON file.
ERROR: Loading design failed.
```
after
```
nextpnr-ice40 --lp384 --json missing.json --pcf constraints.pcf --asc fine.asc
ERROR: failed to open JSON file.
ERROR: Loading design failed.
```
=> Improve error reporting of failure to open JSON file

ecp5/main.cc, generic/main.cc, ice40/main.cc
Clang on macOS was warning about the missing override identifier.
=> Mark getArchOptions as override in derived classes

common/nextpnr.h, common/place_common.cc, common/placer1.cc
Loc::operator!=() had a typo in thus legaliser was not reporting correct stats.
Furthermore, legaliser now returns bool indicating whether something moved or not, which determines whether placer1's temperature should be increased.
=> Fix legalise

ice40/pack.cc
=> ice40: Add warning if an instanciated SB_IO has its PACKAGE_PIN used elsewhere

common/command.cc
In arachne-pnr I found this useful, so I recreated that option. In arachne-pnr, some care is taken to prevent the seed to become zero, so this is present here too. Not sure this needed.
=> add "randomize-seed" command-line option

common/placer1.cc, common/placer1.h
If you have a large grid and very few BELs of a given type, picking a
random grid location yields very little odds of finding a BEL of that
type.
So for those, just put all of them at (0,0) and do a true random pick.
Fixes #127 
=> common/placer1: In random pick, only use grid if there is more than 64 BELs

ice40/pack.cc
=> ice40/pll: Fix typo when testing for global port output net

README.md
UWhen installing Boost, you can either install libboost-all-dev, or install
just the required packages.
Previously, `libboost-dev` was the only required package listed.
This adds `libboost-filesystem-dev libboost-thread-dev libboost-program-options-dev
libboost-python-dev` to the list of required packages.
It addresses issue #128.
Signed-off-by: Sean Cross <sean@xobs.io>
=> README: further specify required Boost packages for Ubuntu

common/command.cc, common/command.h, common/log.cc, common/log.h, common/router1.cc, common/timing.cc, common/timing.h, gui/basewindow.cc
Fixes #136 and #137 
Adds the `--log`/`-l` option, similar to Yosys, to write a log file which contains all messages even if `-q` is set to limit what is printed to the console.
This also attempts to make the log code more orthogonal, adding the concept of log levels and removing some ugliness such as vectors of both C file pointers and C++ streams.
Timing failures are now printed as warnings in post-route timing analysis.
=> Tidy up logging code, add log file support, make timing failures non-fatal errors

ice40/main.cc, ice40/pack.cc
- Disable promotion of 'logic' globals for now, at least until we have a better heuristic for this, and require `--promote-logic` to enable it
- Add `--no-promote-globals` to disable all automatic global promotion
=> ice40: Finer-grained control of global promotion

ice40/pack.cc
On UP5K (at least), any promoted global introduces a significant timing hit, around 4.8 to 6.1 ns. If I am trying to reach a ~35 MHz frequency target in a clock domain (which is about as much as possible to achieve on UP5K), this virtually always breaks timing.
The current threshold is smaller than even a single CLB, which seems obviously wrong. The new threshold would not promote any CE that feeds less three CLBs worth of logic to a global. This is probably still too small, but I'm not sure how to arrive at a proper value.
=> ice40: raise CE global promotion threshold

common/rulecheck.cc, ecp5/arch.cc, ice40/arch.cc, ice40/pack.cc, json/jsonparse.cc
- Replace assertion failure for multiple drivers with a precise error
- Replace the "no timing data" error (the first time that unknown cell types present a problem) with an "unsupported cell type" error that provides a clearer path to a solution in most cases
- Remove the inaccurate "pre-placed design" in rulecheck
- Add a warning for IO pins without a constraint, as this is often a bug in the design
=> Error reporting improvements

ice40/pack.cc
Without this threshold nextpnr would happily promote a reset with fanout 1 to a global.
=> ice40: add reset global promotion threshold

ice40/chains.cc
- @smunaut 's suggestion to include 'I3-only' connectivity during chain finding
- Pass carry up the chain when inserting a feed-through LC to avoid the need to split the chain
=> ice40: Carry chain optimisations

.cirrus.yml, .cirrus/Dockerfile.ubuntu16.04
This is a replacement for #67 . It currently builds nextpnr for all architectures and runs their respective test binaries.
=> ci: implement using CirrusCI

common/timing.cc, common/timing.h, common/timing_opt.cc, common/timing_opt.h, ice40/arch.cc, ice40/main.cc, ice40/picorv32_benchmark.py
This adds `criticality` calculation (ie how close an arc is from becoming the critical path, in [0, 1]) to the timing analysis; and a highly experimental pass for optimising the critical path based on https://www.cerc.utexas.edu/utda/publications/C205.pdf
=> Adding criticality calculation and experimental timing optimisation pass

json/jsonparse.cc
Previously ties were being broken arbitrarily (last name wins). For purposes such as timing constraints/reports this was not useful. Instead this applies a simple heuristic to pick a probably more useful, and at least consistent, name.
=> json: Prefer higher level net names when a net has multiple names

ice40/bitstream.cc, ice40/pcf.cc
Fixes #188; also adds support (including in bitstream gen) for up5k configurable pullup strength, support for PCF `-nowarn` to suppress the warning for unmatched constraints, and a warning for unknown PCF settings.
=> ice40: Add PCF support for -pullup, -pullup_resistor and -nowarn

ecp5/pack.cc
=> ecp5: Check for incorrect use of TRELLIS_IO 'B' pin

common/command.cc
This way errors (such as an invalid package type) occurring
during Context creation are printed properly.
Fixes #192
=> command: Setup logging before attempting to create Context

ice40/arch.cc, ice40/archdefs.h
In particular, DDR inputs and outputs are now correctly considered register inputs/outputs with the appropriate clock domain and edge for timing analysis purposes.
Sample timing report on CSI-2 Rx:
```
Info: Critical path report for clock 'csi_rx_i.dphy_clk' (negedge -> posedge):
Info: curr total
Info:  1.0  1.0  Source $techmap\csi_rx_i.$genblock$../../link/csi_rx_ice40.v:110$333[1].\data_iobuf.D_IN_1
Info:  3.8  4.8    Net raw_ddr[3] budget 40.561001 ns (9,31) -> (5,26)
Info:                Sink $auto$simplemap.cc:496:simplemap_adff$3550_DFFLC.I0
Info:  0.1  4.9  Setup $auto$simplemap.cc:496:simplemap_adff$3550_DFFLC.I0
Info: 1.1 ns logic, 3.8 ns routing
```
The Fmax for this path is also correctly given as 102MHz (halved because it is between different clock edges).
=> ice40: Add timing data for all IO modes

ice40/pack.cc
... rather than assert()-out during the call to getWireBelPins() call
=> ice40: Add error message if a selected site is not Global Buffer capable

ice40/pack.cc
Useful to allow manual placement of EBR using BEL attribute for instance
=> ice40/pack: Copy attributes to packed cell

common/timing.cc, ice40/arch.cc, ice40/arch.h
- Consider combinational fanout from ports that are also register inputs (e.g. iCE40 carry chains/LUTCascade mixed with registers)
- Remove false paths through logic cells with register enabled, that the above would otherwise reveal
- Fix timing classification of PLLOUTGLOBAL
=> [timing] Path related fixes

ice40/pack.cc
Fixes #229 
For single-output PLL variants, we were only checking for conflicts with the first output; but still creating SB_GBs for both outputs.
=> ice40: Don't create PLLOUT_B buffer for single-output PLL variants

ecp5/family.cmake
If a distro-specific "prjtrellis-devel" packaged dependency is used,
the pytrellis.so library might be located in a dedicated directory,
rather than under ${TRELLIS_ROOT}.
Search for pytrellis.so in a list of directories, then subsequently
use the first match as part of ${PYTHONPATH}.
Signed-off-by: Gabriel Somlo <gsomlo@gmail.com>
=> ecp5: cmake: Search for pytrellis.so in multiple locations

ice40/arch.cc
For the `padin` case, the global buffer input is not connected so treating as combinational is not appropriate.
Fixes #237
=> ice40: Fix timing class of 'padin' GB outputs

gui/fpgaviewwidget.cc
right & middle clight are really inconvenient when working with a touchpad
in tap-to-click mode
=> gui: Allow shift+drag to move around the view

ecp5/lpf.cc, ecp5/main.cc
- Better errors (with line numbers) and fewer assertion failures in the LPF parser
- Remove the warning for unmatched constraints; add an error if an LPF file is specified but some IO are unconstrained, with `--lpf-allow-unconstrained` to override (this is identical to the current iCE40 situation)
=> ecp5: Improve constraint-related error handling

ice40/arch.cc
Signed-off-by: Marcin Kościelnicki <marcin@symbioticeda.com>
=> ice40: Fix u4k in external chipdb mode.

README.md
The recent addition of "eigen3" to nextpnr necessitates the addition of
"eigen" to the list of vcpkg packages to be installed on Windows.
Add the 32- and 64-bit versions of eigen to the command issued to
install various dependencies.
Also document one possible build command, and note about unpacking
python36.zip.
Signed-off-by: Sean Cross <sean@xobs.io>
=> README: update windows build instructions for eigen, python

common/command.cc
Using a copy constructor to set the logfile is the only thing that
stops compilation with the libstdc++ shipping with gcc 4.8 (maybe 4.7)
=> common: avoid std::ofstream copy

common/placer1.cc
This further improves incremental bounding box updates by keeping track of the number of cells on each edge of the bounding box, so a full recompute is needed only when the last cell at an edge moves inwards (moves outwards never need a full recompute).
Although there is no significant runtime improvement on small designs, on a large design it gives about a 3x runtime improvement.
=> placer1: Improve incremental bounding box updates

ice40/pack.cc
This is mostly for the benefit of PLL placement because the D_IN_x
ports are used for other purposes when PLL is enabled so we need to
make sure nothing is connected there already. (even an unused net is
too much)
=> ice40/pack: During IO packing, remove any unused input connection

README.md
ice40/blinky.* moved to ice40/examples/blinky/blinky.* in commit 1780f42b9a7854a8a7bf1f2d6589d3d35f133f87
---
The outdated quick-start description was slightly confusing when I was trying to build nextpnr for the first time and quickly check if it was working. Hopefully, this will save someone else the confusion. :)
=> Fix ice40 example directory in README.md

common/timing_opt.cc
Just add lock/unlock calls on the context; this fixes (at least for me) a GUI crash when using --opt-timing. I didn't add a yield() call in the loop, but I could add one if wanted.
=> timing_opt: Add locks to optimise()

common/command.cc, gui/application.cc, gui/application.h
Added option --gui-no-aa to disable anti-aliasing in GUI mode
Way to fix problems like https://github.com/YosysHQ/nextpnr/pull/278 when hardware does not support that level of anti aliasing.
=> option to disable anti aliasing in gui

common/timing.cc
It was annoying me so I fixed it. I also looked at every other log statement and that was the only one missing that I noticed.
=> Fix missing \n in log statement

ecp5/arch.cc, ecp5/globals.cc, ecp5/pack.cc
This way load and save between place/pack and routing works correctly.
=> ecp5: Use an attribute to store is_global

ice40/pcf.cc
This is meant to catch unfortunate mistakes like `set_io <cell> <pin> -pullup yes` that I made recently.
=> ice40: Warn that trailing PCF settings are ignored

common/nextpnr.h, common/placer_heap.cc
In statically linked builds it crash inside std::thread implementation. Switching to boost helps resolving this issue.
#0  0x0000000000000000 in ?? ()
#1  0x000000000042fb8a in __gthread_self () at /usr/include/x86_64-linux-gnu/c++/7/bits/gthr-default.h:686
#2  std::this_thread::get_id () at /usr/include/c++/7/thread:343
#3  nextpnr_ice40::BaseCtx::lock (this=0xe659c00) at nextpnr/common/nextpnr.h:586
=> Switching from std to boost fix crash

ecp5/main.cc, ice40/examples/blinky/blinky.sh, ice40/examples/floorplan/floorplan.sh, ice40/main.cc
This is the first part of a solution to #304, so that we can remove default package value altogether in a month or two, and certainly before the first stable release of nextpnr (whenever that is)
=> Add deprecation warning for default packages

CMakeLists.txt
With newer versions of cmake, an unquoted 6th argument gives the
following error:
STRING sub-command REGEX, mode REPLACE needs at least 6 arguments
total to command.
Quoting this fixes the issue.
Signed-off-by: Sean Cross <sean@xobs.io>
=> cmakelists: quote the last argument to REGEX REPLACE

ecp5/globals.cc
This PR allows optional disabling of the promotion to global of a clock using the `(* ECP5_IS_GLOBAL=0 *)` attribute.
This allows ring oscillators to be used as clock sources. When creating a ring oscillator with Yosys+NextPNR or Diamond and adding it to the sensitivity list, the ring oscillator stops oscillating. This was described in DurandA/verilog-buildingblocks#1.
To the best of my knowledge, this is not possible in Diamond as I couldn't find such a feature in the chapter _Specifying Constraints and Attributes_ from _Lattice Synthesis Engine for Diamond User Guide_. In this regards (and considering that the use-cases are limited), I don't necessarily expect this PR to be accepted.
=> Restrict clock promotion to global on ECP5

ecp5/arch.cc, ecp5/arch.h, ecp5/bitstream.cc
Get rids of the warning mentioned in https://www.reddit.com/r/yosys/comments/crf3e2/bitstream_file_generating_warning/ when using a nextpnr/trellis bitstream with Diamond programmer or other Diamond tools.
=> ecp5: Add full part name to bitstream header

common/nextpnr.cc, common/nextpnr.h, ecp5/arch_pybindings.cc, ice40/arch_pybindings.cc, json/jsonparse.cc
This makes specifying clock constraints on interior nets much easier.
Not the cleanest implementation, but somewhat limited by the current state of the JSON parser, more significant improvements to which are on my TODO list.
=> json: Add support for net aliases

CMakeLists.txt
This is required for builds on Arch Linux, too
=> Apply Boost CMake fix to all OSs

docs/ice40.md, ice40/pcf.cc
Right now the lack of any other timing constraint format limits builds not linked with Python. This should make useful static/distributable builds much smaller and simpler than at present.
Strictly speaking, the vendor-compatible way would be to use sdc files. But this is a bigger project as it applies to multiple architectures and would need more research into a reasonable subset to support (and any IP issues that might affect it). It might even be best to approach that from the Yosys side; as eventually synthesis-time constraints will be needed too (this could then be passed to nextpnr in an attribute).
=> ice40: Add set_frequency pcf command; and document pcf format

ice40/family.cmake
When building using non-pregenerated bba files, the rule to create bbasm
files gets called twice: once unconditionally, and once as part of the
conditional that determines we're not using a pregenerated bba path.
If we _are_ using a pregenerated bba path, then this rule gets called
anyway, resulting in a build error.
Remove the duplicate, unconditional creation of the bba file generation,
to fix the build when using pregenerated files, and to speed up the
build when not using pregenerated files.
=> ice40: cmake: fix build with pregenerated bba path

.gitignore, generic/cells.cc, generic/examples/bitstream.py, generic/examples/simple.py, generic/examples/simple.sh, generic/examples/simple_timing.py, generic/synth/prims.v
Currently the GENERIC_SLICE has one Q output that is either used by the DFF output or by the LUT output. However, it appears that most FPGA architectures have a seperate output for the LUT that bypasses the DFF.
This PR adds an F output to GENERIC_SLICE that is the direct output of the LUT, and removes the FF_USED parameter.
=> Dedicated output for LUT in GENERIC_SLICE

generic/pack.cc
In #350 the LUT output was given its own F port, but the constant LUTs still use the Q port, which is the DFF output. This leads to erratic behavior when the DFF clock is not driven and its reset value does not correspond with the LUT value.
=> leftover Q from before slice api change

common/command.cc, common/design_utils.cc, common/design_utils.h, common/nextpnr.h, common/sdf.cc, ecp5/cells.cc, ecp5/pack.cc, ice40/cells.cc, ice40/pack.cc
SDF timing simulation requires some changes to the Yosys cell library that are still being worked on. Furthermore a closed source simulator (e.g. xsim) seems to be required; iverilog's SDF support seems to be too limited, in particular not supporting interconnect delays.
=> Improve handling of top level IO and add SDF support

bba/main.cc, ice40/family.cmake
Disabled by default. Use `cmake -DUSE_C_EMBED=1` to enable. `#embed_str` is part of [P1040](https://thephd.github.io/vendor/future_cxx/papers/d1040.html).
=> Add bba #embed support

ecp5/bitstream.cc, ecp5/cells.cc, ecp5/pack.cc
This is an undocumented flipflop mode where LSR loads the value from "M" rather than fixed set or reset. This is interesting as it can be used to implement async functions like latches that the ECP5 doesn't otherwise support.
=> ecp5: Add support for flipflops with preload

README.md
Brand new to FPGA ! iverilog, yosys and nextpnr without problems.
Pushing what I believe to be a typo.
Franck
Running on debian/testing:
```
>> cmake -DARCH=generic -DCMAKE_INSTALL_PREFIX=/scratch/fghp/FPGA/nextpnr/local -DBUILD_TESTS=ON ..; make
>> make tests
make: *** No rule to make target 'tests'.  Stop.
>> make test
Running tests...
Test project /scratch/fghp/FPGA/nextpnr/build
Start 1: generic-test
1/1 Test #1: generic-test .....................   Passed    0.01 sec
100% tests passed, 0 tests failed out of 1
Total Test time (real) =   0.01 sec
```
=> [DOC] Fixing typo: cmake test suite triggered by 'make test'.

README.md
libboost-iostreams-dev needs to be installed on a fresh debian: guess this one was omited.
=> [README] Add prerequisite: libboost-iostreams-dev.

CMakeLists.txt, common/command.cc, common/version.h.in, json/jsonwrite.cc
Change version to use git describe instead of git log as this will also work
if tags are present and make the version string set-able from outside as a
parameter to cmake, so that package managers can set this if building outside
of a git working tree.
=> Change version to git describe and make set-able from outside

3rdparty/QtPropertyBrowser/src/qteditorfactory.cpp, 3rdparty/QtPropertyBrowser/src/qttreepropertybrowser.cpp, 3rdparty/QtPropertyBrowser/src/qtvariantproperty.cpp, 3rdparty/imgui/imgui_internal.h, ecp5/gfx.cc, frontend/json_frontend.cc, generic/pack.cc, gui/treemodel.cc
Various fixes of warnings in nextpnr code.
@daveshah1 one with json_frontend.cc is due to typedef already being const others are quite straight forward
warning: 'const' qualifier on reference type 'nextpnr_generic::JsonFrontendImpl::ModuleDataType' (aka 'const json11::Json &') has no effect [-Wignored-qualifiers]
=> Warning fixes

3rdparty/json11/json11.cpp, frontend/json_frontend.cc, json/jsonwrite.cc
See YosysHQ/yosys#1671 for rationale.  Also, added some validation
to our parser, so that out-of-range values are reported and the user
knows they should update yosys.
=> json: fix handling of 32-bit parameters

common/command.cc, common/nextpnr.h, common/placer1.cc, common/router1.cc, common/router2.cc, common/router2.h, docs/archapi.md, ecp5/arch.cc, ecp5/arch.h, ecp5/arch_place.cc, generic/arch.cc, generic/arch.h, ice40/arch.cc, ice40/arch.h
router2 is a negotiated congestion based router, based on CRoute (DOI 10.1109/FCCM.2019.00017). Its primary intention is in preparation Xilinx flows where congestion is a serious problem, it has limited benefit for existing arches. It also currently carries a timing cost compared to router1 but this is more due to having fewer timing heuristics at present. As a result router1 remains the default for all current arches, and will do for the near future.
This is only the first phase of development, I have future plans for SAT to deal with difficult congestion conflicts, a special pass for high-fanout nets and timing-driven ripup in the future. It also currently relies on router1 to check the route is valid, I hope to remove this eventually.
=> Upstreaming router2

.cirrus.yml, .cirrus/Dockerfile.ubuntu16.04, README.md, ecp5/family.cmake
Rebased, updated and squashed commits by @jboone on jboone/nextpnr@246fff9
(also mentioned in #272)
Necessary, if prjtrellis or rather libtrellis is install to a custom install path (e.g. `/opt/prjtrellis/`),
then `cmake -DARCH=ecp5 -DTRELLIS_ROOT=/opt/prjtrellis` did not found pytrellis library etc.
=> Fix paths to prjtrellies project

common/placer1.cc, common/placer1.h, common/placer_heap.cc, common/placer_heap.h
- Making beta configurable to increase spreading (needed for the fact there are two bels per LUT6)
- Spreading LUTs, carries and FFs together, as they are closely linked
- Weighting HPWL differently in X and Y directions, to account for the tile pattern of Xilinx-style FPGAs with separate interconnect and logic columns
- Adding a disabled-by-default routeability optimisation to placer1 that aims to encourage sharing of tile nets
=> Backporting some placer changes from nextpnr-xilinx

gui/treemodel.cc
std::sort() requires the comparison function to return false for even
comparison. Returning true results in undefined behavior and a potential
segfault.
=> gui: Fix undefined behavior in TreeModel.

ecp5/family.cmake, ice40/family.cmake
If the user specifies a custom install prefix, chances are icestrom/trellis
are also in that prefix rather than the hardcoded /usr/local
Fixes #351
=> build: Default the ECP5 and iCE40 roots to the install prefix

common/pycontainers.h
We raise a C++ exception to abort the rest of the execution of
the function.
At the same time we standardize on using a throw runtime error as the
method to avoid warning when not returning values. (some places
used this throw and some other used std::terminate)
Fixes #403
=> pycontainers: Properly handle KeyErrors

ice40/arch.cc
Wrong bits were being tested. [5:4] is what's controlling the output
enable path.
=> ice40: Fix output register timing analysis for registered output enable

ecp5/bitstream.cc
- Lattice component EHXPLLL parameter compatibility, allowing to
pass an int parameter for the enum (as expected by trellis tile)
e.g. CLKOP_TRIM_DELAY : integer := 0;
=> Enum/int compatibility for EHXPLLL parameters

ecp5/docs/primitives.md
Tested and verified working: the trivial configuration:
module USRMCLK( USRMCLKI, USRMCLKTS );
input USRMCLKI, USRMCLKTS;
endmodule
module top( input clk );
reg[ 24:0 ] count = 0;
always @( posedge clk ) begin
count <= count + 1'b1;
end
USRMCLK mspi( .USRMCLKI( count[ 20 ] ), .USRMCLKTS( count[ 24 ] ) );
endmodule
produces the expected output (toggling at high frequency, toggling
tri-state at lower frequency) on an LFE5U-85 when fed with an appropriate
clock.  See https://bayimg.com/AAnNKAAGO for an example.  The top
(magenta) trace is the MCLK line.
=> Remove comment about the USRMCLK primitive being untested.

ecp5/lpf.cc
Trying to parse this invalid LPF syntax:
LOCATE COMP "a" SITE "A1"
IOBUF PORT "a" IO_TYPE=LVCMOS33;
(note missing semicolon on first line) gives an assertion failure in
strip_quotes, because the fifth token is scanned as "A1"IOBUF (without
a trailing quote).
Avoid the problem by detecting extraneous input and issuing a more
specific error.
=> Fix assertion failure on invalid LOCATE input.

common/design_utils.cc
Without this the python bindings can't actually connect anything else
to a disconnected port since the assert in connect_ports will think
it's still connected
=> design_utils: Set port.net to null when disconnecting

3rdparty/python-console/modified/pyinterpreter.cc, common/pycontainers.h
Fixes #430 
Fixes #431 - autocomplete still isn't very useful but I suspect that is a Python issue rather than anything we can fix, and it doesn't crash any more.
=> python: Miscellaneous fixes

ecp5/arch.cc, ecp5/archdefs.h, ecp5/pack.cc
If the REG_INPUTA_CLK and REG_INPUTB_CLK values are set, then we should
use the faster setup/hold timings for the 18x8 multiplier.
Similarly, check the value of REG_OUTPUT_CLK for whether or not to use
faster timings for the output.
This is based on how I currently understand the registers to work - if
anyone knows the actual rules for when each timing applies please do
chime in to correct this implementation if necessary.
Along the same lines, this PR does not address the case when the
pipeline registers are enabled, since it is not clear to me how exactly
that affects the timing.
=> Alter MULT18X18D timing db based on register config

ecp5/main.cc, generic/main.cc, ice40/main.cc
Hello nextpnr developers!
I've been working lately to package nextpnr for Debian, and one of the things that popped up during that process is that "unsupported" happens to be misspelled in a few places.
Thanks, and happy hacking!
Nate Graff
=> Fix spelling of 'unsupported'

CMakeLists.txt, common/nextpnr.cc, common/nextpnr.h, common/placer_heap.cc, common/router2.cc, ecp5/arch.cc, ecp5/family.cmake, ice40/arch.cc
This involves very few changes, all typical to WASM ports:
* WASM doesn't currently [support threads](https://github.com/WebAssembly/threads) or atomics so those are disabled.
* WASM doesn't currently [support exceptions](https://github.com/WebAssembly/exception-handling) so the exception machinery is stubbed out.
* WASM doesn't (and can't) have mmap(), so an [emulation library](https://github.com/WebAssembly/wasi-libc/blob/master/libc-bottom-half/mman/mman.c) is used. That library currently doesn't support `MAP_SHARED` flags, so `MAP_PRIVATE` is used instead.
There is also an update to bring ECP5 bbasm CMake rules to parity with iCE40 ones, since although it is possible to embed chipdb into nextpnr on WASM, a 200 MB WASM file has very few practical uses.
The README is not updated and …
=> Port nextpnr-{ice40,ecp5} to WASI

ice40/bitstream.cc
This requires the matching chipdb update from icestorm project !
=> ice40: Add support for the 2nd bit of SHIFTREG_DIV_MODE

README.md
Gaffe is completely gone for unknown reasons, KinglerPAR is just an empty repository
=> Remove dead links from README

CMakeLists.txt, README.md, bba/CMakeLists.txt, ecp5/CMakeLists.txt, ecp5/arch.cc, ecp5/arch.h, ecp5/family.cmake, ecp5/resource/chipdb.rc, ecp5/trellis_import.py, ice40/CMakeLists.txt, ice40/arch.cc, ice40/arch.h, ice40/family.cmake, ice40/resource/chipdb.rc
This addresses a lot of different issues:
* The build system logic that handles the `.bba` files is massively simplified.
* `.bba` files can now be built separately from the rest of nextpnr, simplifying pre-generation and cross-compilation.
* `.bba` files can now be included into the binary using any desired approach (selected by the internal variable `BBASM_MODE`), independent from whether they are built separately or from the selected compiler. The default behavior is unchanged, with the exception that non-MSVC Win32 binaries also use the more efficient approach of using resource files.
* The generation of `.bba` files is now serialized across a multi-architecture build, avoiding OOMs caused by building iCE40 and ECP5 chipdbs in parallel.
* Both iCE40 and ECP5 can now be subsetted to …
=> CMake: rewrite chipdb handling from ground up

ice40/pack.cc
=> ice40: If IO is used by SB_GB_IO, can't use it for PLL

ecp5/baseconfigs.cc, ecp5/bitstream.cc, ecp5/config.cc, ecp5/config.h, ecp5/lpf.cc
This allows config-related options to be specified in the SYSCONFIG line of the lpf file, compatible with Diamond's behaviour, like
```
SYSCONFIG CONFIG_IOVOLTAGE=3.3 COMPRESS_CONFIG=ON MCCLK_FREQ=62 MASTER_SPI_PORT=DISABLE SLAVE_SPI_PORT=DISABLE SLAVE_PARALLEL_PORT=DISABLE;
```
(example from ULX3S)
rather than the options either needing to go on the ecppack command line, or in some cases not being supported at all.
It depends on YosysHQ/prjtrellis#146 for these options to be processed after being included in the .config file.
=> ecp5: SYSCONFIG in LPF support

ecp5/lpf.cc
This will likely become an error after a bedding-in period to make sure that nothing has been missed.
=> ecp5: Add a warning for unknown LPF IOBUF attrs

ecp5/pack.cc
In particular this fixes the I/O DDRX2 on the same pin use case.
=> ecp5: Fix how ODDRX2 SCLK/RST are set

common/command.cc, common/nextpnr.h, common/timing.cc
In order to make debugging the critical path easier, print the location of the net definitions where known.
This output is on by default, but may be disabled by passing the `--no-print-critical-path-source` flag.
Example output:
```
Info: Critical path report for clock 'clk_48mhz_$glb_clk' (posedge -> posedge):
Info: curr total
Info:  0.5  0.5  Source driver.pixels_to_shift_SB_DFFE_Q_6_D_SB_LUT4_O_LC.O
Info:  0.6  1.1    Net driver.pixels_to_shift[0] budget 0.000000 ns (5,25) -> (5,25)
Info:                Sink driver.pixels_to_shift_SB_LUT4_O_I3_SB_CARRY_I1_CO_SB_CARRY_CO_4_CI_SB_LUT4_O_LC.I3
Info:                Defined in:
Info:                  top.v:122.7-138.6
Info:                  panel_driver.v:135.44-135.63
Info: …
```
=> Add option to print critical path source code

common/command.cc, common/command.h, gui/ecp5/mainwindow.cc, gui/ice40/mainwindow.cc
When nextpnr is started with `nextpnr-ice40 --hx8k --package ct256 --gui ` after loading JSON from GUI it would switch to default architecture and package ignoring command line parameters. 
This patch makes sure that currently set command line parameters are effective until "New" option is set and target FPGA is changed.
=> Preserve cmd parameters  when loading json from GUI

CMakeLists.txt
See https://lists.j-core.org/pipermail/j-core/2020-September/000940.html
=> Building nextpnr on Devuan ascii 2.0 needs the "C" language enabled.

.cirrus/Dockerfile.ubuntu16.04, generic/synth/synth_generic.tcl
Since the dfflegalize changes, the current script leaks DFF cells, which need to be converted to the right type to synth correctly.
Note this assumes the generic flop initialises to zero. Not 100% sure if this is correct, but supplying `x` will fail to synth anything that uses an init value at all.
=> Update generic synth script for dfflegalize changes

docs/constraints.md
It looks like nextpnr does support quite a lot more constraints than currently documented. This is a first attempt to fix this. Please note that i only checked if nextpnr does accept the constraints without an error or warning, i did NOT test if they have an effect on real hardware. Maybe this should be done before merging my changes, but at least with this pull request there is a notice about the need to update the doc.
=> update doc for ECP5 constraints

common/arch_pybindings_shared.h, docs/archapi.md, docs/generic.md, ecp5/arch.h, generic/arch.cc, generic/arch.h, generic/arch_pybindings.cc, ice40/arch.h
It has not actually been implemented in any router for over 2.5 years and causes nothing more than confusion. It can always be added back if it forms part of a future solution; possibly as part of a more general database structure rethink.
=> Remove wire alias API

ice40/pack.cc
It's been confirmed that :
(1) this is required by the hardware
(2) icecube will force that field to 4'b1111 in fixed mode
=> ice40/pack/SB_PLL: Force fixed value to 4'b1111 if dynamic delay is used

3rdparty/python-console/modified/pyinterpreter.cc
Using interpreter created by main thread instead of creating new one. Helps solving some GIL related issues.
=> Do not create new python interpreter

ecp5/arch.h, ice40/arch.h
These operations are meaningless for a data structure that references another structure relative to its location.
cc @pepijndevos
=> RelPtr: remove copy constructor and copy assignment

common/command.cc, common/pybindings.cc, common/pybindings.h, gui/pythontab.cc
Use pybind11 capabilites to get more clean and stable code. It is now possible to use python console in GUI after context change (new device selected)
Note to future self:
PYBIND11_EMBEDDED_MODULE -> also include PyImport_AppendInittab
py::initialize_interpreter -> also include adding current path to sys.path
=> Python code cleanup

.cirrus.yml, CMakeLists.txt, README.md
Following large numbers of [GUI-related issues](https://github.com/YosysHQ/nextpnr/issues?q=is%3Aissue+qt5), it seems like disabling the GUI by default is going to be the path of least resistance, given that the command line flow is what most people are primarily using.
=> cmake: Disable building GUI by default

common/nextpnr.h, common/placer_heap.cc
std::random_shuffle deprecated in C++14 and was removed in C++17.
=> C++17 compatibility: Don't use std::random_shuffle

.cirrus/Dockerfile.ubuntu20.04, gowin/CMakeLists.txt
I've updated Apicula to generate a Chipdb for the GW1N-4 family of devices, for which this PR adds the bba to the build systems and the CI build.
Seems to work: https://twitter.com/pepijndevos/status/1345747194155040770
=> Gowin: Add GW1N-4 support

docs/coding.md, ecp5/arch.cc, ecp5/arch.h, ecp5/arch_place.cc, ecp5/bitstream.cc, ecp5/globals.cc, ecp5/lpf.cc, ecp5/main.cc, ecp5/pack.cc, gui/ecp5/mainwindow.cc, gui/ice40/mainwindow.cc, ice40/arch.cc, ice40/arch.h, ice40/arch_place.cc, ice40/chains.cc, ice40/main.cc, ice40/pack.cc, ice40/pcf.cc
This improves the ability to distinguish between what is part of the official Arch API and what is arch-specific.
Longer term, there are potentially better ways to do this like https://github.com/SymbiFlow/nextpnr/pull/195#discussion_r566203422 (potentially with their own complexities) but this is a first step in that direction to improve the clarity.
An annoying exception here is the nextpnr-generic `add*` functions; which can't be renamed without a breaking change to downstream users of the Python API, which I try and keep stable without very good reasons for change.
=> Use snake case consistently for non-Arch-API functions

common/archcheck.cc, common/nextpnr.cc, common/nextpnr.h, generic/arch.cc, generic/arch.h, generic/arch_pybindings.cc, gowin/arch.cc, gui/designwidget.cc, ice40/arch.cc, ice40/arch.h, ice40/arch_pybindings.h, nexus/arch.cc, nexus/arch.h, nexus/arch_pybindings.h, nexus/fasm.cc, nexus/pack.cc
Non-explicit single argument constructors will silently convert to that type.  This
is typically not the right thing to do.  For example, the nexus and
ice40 arch_pybindings.h files were incorrectly parsing bel name strings,
etc.
I discovered this issue when checking the python API.
=> Mark IdString and IdStringList single argument constructors explicit.

common/nextpnr.h, docs/archapi.md, ecp5/arch.cc, ecp5/arch.h, ecp5/arch_pybindings.h, ecp5/archdefs.h, fpga_interchange/arch.cc, fpga_interchange/arch.h, generic/arch.h, gowin/arch.cc, gowin/arch.h, ice40/arch.cc, ice40/arch.h, ice40/arch_pybindings.h, ice40/archdefs.h, nexus/arch.cc, nexus/arch.h, nexus/arch_pybindings.cc, nexus/arch_pybindings.h, nexus/archdefs.h
This creates a new `BaseArch` layer which `Arch` inherits from, and which implements the `Arch` functions virtually with a struct of `using`s as a template parameter for the functions where the return type is Arch-defined (as suggested in https://github.com/SymbiFlow/nextpnr/pull/195#discussion_r566203422 ).
Some further template magic is used to provide default implementations when the range types comply to certain traits or error out otherwise.
Things still to consider:
cc @ravenslofty @litghost
=> Create a new BaseArch that formally specifies the Arch API and provides some base implementations 

common/nextpnr.h, docs/archapi.md, ecp5/arch.h, ice40/arch.h, nexus/arch.h
This reduces the amount of per-arch code a bit more.
=> Add BaseArchRanges for default ArchRanges types

common/nextpnr.cc, common/nextpnr.h, common/pybindings.cc, gui/designwidget.cc
No arches ever actually used this to implement a Cell->Bel pin mapping, and in practice if any did try they would inevitably hit bitrot.
This field had limited use in practice as it is necessary to also support cases where one cell pin maps to more than one bel pin. Removing this old field is the first step towards developing a new API for this.
=> Remove the unused CellInfo::pins field

common/nextpnr.cc, common/nextpnr.h, common/router1.cc, common/router2.cc, common/timing.cc, docs/archapi.md, fpga_interchange/arch.h, generic/arch.cc, generic/arch.h, gowin/arch.cc, gowin/arch.h, nexus/global.cc
This adds a new Arch API to request the range of bel pin(s) that correspond to a cell pin and provides a trivial implementation for all arches. It is primarily a RFC to work out the kinds of changes that the router etc would need to use such an API at this stage.
Outstanding issues: 
Fixes #560
=> Support for cell pin to bel pin mappings

common/nextpnr.h, common/place_common.cc, common/placer1.cc, common/placer_heap.cc, docs/archapi.md, docs/coding.md, ecp5/arch.h, ecp5/arch_place.cc, ecp5/arch_pybindings.cc, ecp5/globals.cc, fpga_interchange/arch.h, fpga_interchange/arch_pybindings.cc, generic/arch.cc, generic/arch.h, gowin/arch.cc, gowin/arch.h, ice40/arch.h, ice40/arch_place.cc, ice40/arch_pybindings.cc, machxo2/arch.cc, machxo2/arch.h, machxo2/arch_pybindings.cc, nexus/arch.h, nexus/arch_place.cc
This Arch API dates from when we were first working out how to implement placement validity checking, and in practice is little used by the core parts of placer1/HeAP and the Arch implementation involves a lot of duplication with isBelLocationValid.
In the short term; placement validity checking is better served by the combination of checkBelAvail and isValidBelForCellType before placement; followed by isBelLocationValid after placement (potentially after moving/swapping multiple cells).
Longer term, removing this API makes things a bit cleaner for a new validity checking API.
=> Remove isValidBelForCell

common/bits.cc, common/bits.h
This library captures use of __builtin_popcount and __builtin_ctz on
GCC/clang and hopefully handles the MSVC case.
=> Add a Bits utility library.

CMakeLists.txt
Depending on the exact compiler and/or libc this can still [cause issues](https://github.com/YoWASP/nextpnr/runs/1983657117?check_suite_focus=true) similar to the ones that arise from blanket enabling `-Werror`:
```
ccache /usr/bin/ccache /home/whitequark/Projects/yowasp/nextpnr/wasi-sdk-11.0/bin/clang++ -DARCHNAME=ecp5 -DARCH_ECP5 -DBOOST_AC_DISABLE_THREADS -DBOOST_EXCEPTION_DISABLE -DBOOST_NO_CXX11_HDR_MUTEX -DBOOST_NO_EXCEPTIONS -DBOOST_SP_NO_ATOMIC_ACCESS -DEXTERNAL_CHIPDB_ROOT=\"/share\" -DMAIN_EXECUTABLE -DNEXTPNR_NAMESPACE=nextpnr_ecp5 -DNO_GUI -DNO_PYTHON -DNPNR_DISABLE_THREADS -DWITH_HEAP -I/home/whitequark/Projects/yowasp/nextpnr/nextpnr-src/common -I/home/whitequark/Projects/yowasp/nextpnr/nextpnr-src/json -I/home/whitequark/Projects/yowasp/nextpnr/nextpnr-src/frontend …
```
=> cmake: Don't enable any -Werror flags without opt-in

common/nextpnr.cc, common/nextpnr.h
This API was simply an attractive nuisance as no code was ever developed to actually process timing constraints (other than clock constraints which use a different API).
While I do want to consider basic false path support, among other things, in the near future; I plan for this to use a new API that doesn't add complexity to the BaseCtx/Context monstrosity and that is easier to use on the timing analysis side.
=> Remove unused advanced timing constraint API

gowin/arch.cc, gowin/archdefs.h
Under the old generic target, only plain simple DFF were supported, but the new target supports all sorts of exotic reset modes and it turns out this was not tested very well at all.
This fix makes sure that no two DFF of different types can occupy the same slice.
There is at least 1 more bug of this kind, so feel free to leave this open, or merge and I'll make new PRs as I fix more bugs.
=> Gowin DFF fixes

nexus/arch.h
This gets archcheck, at least, passing for the LIFCL-17 device
=> Fix global normalisation for LIFCL-17

CMakeLists.txt, common/router2.cc
Abseil has a hard dependency on threads (not just in the build system but in many places in the base libraries), so there is no way to use it on WASI at the moment. Assuming that Abseil will only be used for speed and not because it provides a richer API, I suggest this workaround.
Fixes #616.
=> Only depend on Abseil in threaded builds.

common/timing_opt.cc
=> opt-timing: Skip undriven nets

common/nextpnr.cc, common/nextpnr_assertions.h
These were omitted in #621 (some because they are not exercised in non-WASI builds, some because libstdc++ is not very hygienic with headers).
=> Add missing includes to fix WASI build

CMakeLists.txt, fpga_interchange/family.cmake, gui/CMakeLists.txt
- Allow `gui_${family}` library to be linked against libraries that expose headers.  This is important if `archdefs`/etc use headers
- Enable IPO on builds
- Allow optional linking against `libprofiler`.
=> Update root CMake with some additional features

CMakeLists.txt
Based on the CMake docs:
> Set <result> variable to YES if IPO is supported by the compiler and NO otherwise. If this option is not given then the command will issue a fatal error if IPO is not supported.
I think this should fix the WASM issue but haven't actually tested (is there an easy way to test locally?)
=> cmake: Use IPO only if supported

common/nextpnr_namespaces.h, fpga_interchange/arch.cc, fpga_interchange/arch.h, fpga_interchange/arch_iterators.h, fpga_interchange/archdefs.h, fpga_interchange/chipdb.h, fpga_interchange/luts.cc, fpga_interchange/xdc.cc, fpga_interchange/xdc.h
This is part 1 of many splitting up #627 
This mostly code movement between headers as needed, with some assorted cleanup and fixes.
=> Refactor header structures in FPGA interchange Arch.

common/arch_api.h, common/base_arch.h, common/router2.cc, docs/archapi.md, fpga_interchange/arch.cc, fpga_interchange/arch.h, generic/arch.cc, generic/arch.h
This is important for distinguishing valid pseudo pips in the FPGA
interchange arch. This also avoids a double or triple lookup of
pip->net map.
=> Add "checkPipAvailForNet" to Arch API.

fpga_interchange/site_router.cc
Found during some early Nexus testing
=> interchange: Add nice error for missing cell pins

.github/ci/build_interchange.sh, common/dynamic_bitarray.h, common/property.h, fpga_interchange/arch.cc, fpga_interchange/arch.h, fpga_interchange/cell_parameters.cc, fpga_interchange/cell_parameters.h, fpga_interchange/chipdb.h
This requires a new release of the `python-fpga-interchange` lib, which hasn't been cut yet.
=> Update parameter processing based on new DeviceResources metadata

.github/ci/build_interchange.sh, common/dynamic_bitarray.h, common/property.h, fpga_interchange/arch.cc, fpga_interchange/arch.h, fpga_interchange/cell_parameters.cc, fpga_interchange/cell_parameters.h, fpga_interchange/chipdb.h, fpga_interchange/site_arch.h, fpga_interchange/site_arch.impl.h, fpga_interchange/site_router.cc, fpga_interchange/site_routing_cache.cc, fpga_interchange/site_routing_cache.h
Initial version of inverter logic.
For now just implements some inspection capabilities, and the site router (for now) avoids inverted paths.
PR extends #639.  This requires a new release of the `python-fpga-interchange` lib, which hasn't been cut yet.
=> Initial inverter logic for FPGA interchange

fpga_interchange/dedicated_interconnect.cc, fpga_interchange/dedicated_interconnect.h
This occurs when the driver pin and sink pin are part of the same site,
but not reachable with site routing only.
=> Fix bug where DedicateInterconnect incorrectly allows some placements.

.cirrus.yml
Cirrus CI now requires that RAM (in GiB) be less than 4*vCPU.
Example failure: https://cirrus-ci.com/task/5969551172042752
=> Increase vCPU to 5 because of cirrus resource limit change.

.github/ci/build_interchange.sh, .github/workflows/interchange_ci.yml
This way things can be merged into master that necessitate other changes without breaking the CI.
Ideally this would use tags long term but prjoxide isn't quite stable enough yet, this should suffice for now.
cc @acomodi
=> interchange: Pin prjoxide commit in CI

common/placer_heap.cc
I found this a while ago working on the ECP5 DSP but since it looks like this is the only other placer-related change it probably makes sense to PR it separately. Currently the CutSpreader `init()` has two loops over `p->cell_locs`, the first skips fixed cells and cells with high `belStrength`, but the second only skips fixed cells. As far as I could tell this is just an omission; if my design has some user-placed cells inside a cellGroup (using a manual `bel` attribute) then nextpnr throws an out of range exception without this change.
=> HeAP: Skip high-strength cells in both cell loops

ecp5/arch.cc, ecp5/bitstream.cc, ecp5/pack.cc
This PR uses cellGroups to allow nextpnr to place an ECP5 ALU54B correctly adjacent to the connected MULT18X18Ds, allowing use of the ALU without having to manually place all components.
Manual placement of both the ALU and MULT still works, but we detect trying to manually place only the MULT(s) or only the ALU and error out, since I found only specifying half the locations did not work with the placer.
There's a couple other relevant commits included:
* 9538954 adds a missing parameter `REG_OPCODEOP1_1_CLK` which is already in the prjtrellis db and yosys cell
* d4c6882 adds the placement constraints described above
* b6c608e adds a few checks to the placer to detect invalid MULT+ALU connections; all these scenarios are rejected outright by Diamond but currently ignored by nextpnr, …
=> ECP5 ALU54B placement support

common/bits.h
Fixed the variable name for windows MSVC builds. I didn't test this build locally but [the log](https://github.com/davidcorrigan714/nextpnr-actions-prototype/runs/2472076784?check_suite_focus=true#step:13:2729) on the GitHub action I've been running seems pretty conclusive this is the culprit.
=> Fix variable name in bits.h for MSVC builds

common/arch_api.h, common/base_arch.h, common/base_clusterinfo.h, common/basectx.cc, common/nextpnr_types.cc, common/nextpnr_types.h, common/place_common.cc, common/placer1.cc, common/placer_heap.cc, common/timing_opt.cc, docs/archapi.md, docs/netlist.md, ecp5/archdefs.h, ecp5/bitstream.cc, ecp5/pack.cc, fpga_interchange/arch.h, fpga_interchange/archdefs.h, generic/arch.h, generic/archdefs.h, gowin/archdefs.h, ice40/archdefs.h, ice40/chains.cc, machxo2/archdefs.h, nexus/archdefs.h, nexus/pack.cc, nexus/post_place.cc
This PR describes a new way of representing clusters to give considerably more flexibility to the architecture as to how cells are placed relative to each other; compared to the existing `constr_{x, y, z}` approach.
In particular, this approach can enable architectures to represent:
- carry chains with discontinuities in the relative coordinates, for example due to clocking rows
- IO-IOLOGIC connectivity which may be better defined by the routing graph than by relative coordinates
- intra-site dedicated routing where the `z` coordinates aren't meaningful, and using bel names or routing to define constraints makes more sense.
Currently this PR only contains the API specification and not any implementation. I'd really appreciate some feedback before I start working on implementation, …
=> New cluster API

.github/workflows/interchange_ci.yml, fpga_interchange/arch.cc, fpga_interchange/arch.h, fpga_interchange/chipdb.h, fpga_interchange/globals.cc
This currently implements very simple BFS-based global routing for clock buffer outputs (other features are WIP). It produces plausible results on the counter test but hits some issues on the RAM test relating to site pin conflicts, currently.
It's on top of #693.
=> interchange: Initial global routing implementation

fpga_interchange/site_router.cc, fpga_interchange/site_routing_storage.h
This is an attempt at solving the issue described in this comment: https://github.com/SymbiFlow/python-fpga-interchange/issues/76#issuecomment-832759322.
Basically, a site-thru PIP should not be allowed in the cases where the a BEL is not in the same site of the site-thru PIP. The change in this PR is rather strict, as if a net has multiple sinks in different sites, the PIP is automatically considered illegal, even though the actual sink BEL of that connection resides in the same site.
cc @gatecat
=> interchange: fix site-thru pip legality

common/router2.cc, fpga_interchange/arch.cc
@acomodi this should fix the most acute part of the regression coming from #697 - at least it does for the RAM test, I haven't actually tried Murax. There are definitely some other issues with routing though, that I'm continuing to investigate.
=> interchange: Fix bounding box computation

fpga_interchange/arch.cc, fpga_interchange/site_router.cc, fpga_interchange/site_router.h
During general routing, the only site pips that can be allowed are those which connect a site wire to the routing interface. Or, in more general terms, all the PIPs connecting a driver to the routing interface.
This patch though might be too restrictive when dealing with architectures that require more than one site PIPs to route from a driver within a site to the routing interface (which is something that should be allowed in the interchange).
After all, backtracking to validate a path might still be required, as https://github.com/YosysHQ/nextpnr/pull/695 is not enough to cover the faulty edge-cases, where a series of PIPs were used to completely route thru a site.
=> interchange: arch: do not allow site pips within sites

fpga_interchange/pseudo_pip_model.cc, fpga_interchange/site_router.cc, fpga_interchange/site_router.h
This PR fixes https://github.com/SymbiFlow/python-fpga-interchange/issues/76. It allows to store site LUT-thrus that are used during site routing, so that, during the general routing step, the pseudo tile PIPs are correctly blocked by the lut equation.
=> interchange: pseudo pips: fix illegal tile pseudo PIPs

mistral/arch.h
One less TODO in the codebase is always a good thing, right?
=> mistral: add getChipName

mistral/bitstream.cc, mistral/main.cc
This is required for JTAG programming to work, which doesn't support compression - see https://github.com/trabucayre/openFPGALoader/issues/86#issuecomment-849342654
cc @Ravenslofty @trabucayre
=> mistral: Make RBF compression optional

.github/ci/build_interchange.sh, .github/workflows/interchange_ci.yml, fpga_interchange/arch.cc, fpga_interchange/arch.h, fpga_interchange/arch_pack_clusters.cc, fpga_interchange/chipdb.h, fpga_interchange/examples/tests.cmake, fpga_interchange/examples/tests/counter/counter.v, fpga_interchange/examples/tests/counter/run_xilinx.tcl, fpga_interchange/fpga_interchange.cpp, fpga_interchange/site_router.cc, fpga_interchange/site_routing_cache.cc, fpga_interchange/site_routing_cache.h
This PR is based on the ideas of https://github.com/YosysHQ/nextpnr/pull/703, and aims at providing an implementation of the clustering support, so that the placer can be guided by information defined in the chip info.
The current state of developement, combined with https://github.com/SymbiFlow/python-fpga-interchange/pull/91, is able to get a working counter test that uses carry-chains.
TODO:
NOTE:
- The murax test design is not meant to be checked in, but is only useful in the various developement iterations.
=> interchange: enable clusters support

fpga_interchange/fpga_interchange.cpp
This fixes multiple instances of null nets being generated in the physical netlist
=> interchange: fix phys net writer

fpga_interchange/arch.cc
This enables instantiating IO macros
=> interchange: arch: move macro expansion step before ios packing

fpga_interchange/pseudo_pip_model.cc
This is required for UltraScale+ HDIOLOGIC sites, where both `OPTFF` and `OPFF`/`TFF` drive the same wires:
=> interchange: Allow site wires driven by more than one bel

common/command.cc, common/context.h, gui/basewindow.cc
In case we already have at least some design loaded, we reinitialize whole context on loading new JSON file.
Also remove cleanup code which was not enough anyway to make this properly working/
=> Preserve ArchArgs and reinit Context when applicable in GUI, fixes  #737

fpga_interchange/dedicated_interconnect.cc
This relaxes the detailed routing check when verifying that there is a dedicated connection. Instead of returning `false` whenever the max depth is reached, the loop is continued instead to check other expansion branches.
For instance, the ISERDESes `D` input pin could never be found, as a set of routing nodes was traversed, making the dedicated inteconnect from IOB to D impossible, by prematurely returning `false`.
In addition, the max depth is calculated only for routing nodes.
=> interchange: fix dedicated interconnect exploration

fpga_interchange/fpga_interchange.cpp
This solves https://github.com/Xilinx/RapidWright/issues/196.
Nets which do not have any users should not be emitted, or otherwise the DCP generated out of a physical netlist with such nets will not be readable, producing the errors described in https://github.com/Xilinx/RapidWright/issues/196
=> interchange: phys: do not output nets which have no users

fpga_interchange/arch.cc
This is needed for UltraScale+ clock buffer macros, which contain constant sources in some cases that must be folded.
=> interchange: Fix handling of constants in macros

fpga_interchange/fpga_interchange.cpp
This was otherwise failing on UltraScale+ where some of the constant sources are nodes rather than tile/site wires.
=> interchange: Handle case where routing source is a node

.cirrus/Dockerfile.ubuntu20.04, gowin/CMakeLists.txt, gowin/main.cc
This PR add support for GW1NS-2(C) gowin variant:
1. list of gowin devices is updated to add new variant
2. regexp is updated too to support UX type, and option C extension (ARM processor support)
3. family variable is updated to add a possible S extension
=> add support for GW1NS-2 family

.github/workflows/interchange_ci.yml, fpga_interchange/arch.h, fpga_interchange/arch_pack_clusters.cc, fpga_interchange/chipdb.h, fpga_interchange/dedicated_interconnect.cc
This adds the possibility to cluster cells belonging to different sites (e.g. IDELAY -> IDELAYCTRL). To avoid spending useless time discovering valid BELs for only in-site clusters, I have added an additional piece of data to the [clustersPOD](https://github.com/SymbiFlow/python-fpga-interchange/pull/107).
The PR is marked as WIP as I have removed a detailed check for the dedicated interconnects which I think should be done, but might require a restructuring due to being quite expensive. Upon building the context, all the dedicated interconnects are pre-calculated. We can potentially enhance the pre-computed structures with additional data, avoiding us to perform a detailed check once again. I'll need to investigate a bit more what can be a better way of performing this check.
=> interchange: reduce run-time to check dedicated interconnect

fpga_interchange/arch_pack_io.cc, fpga_interchange/dedicated_interconnect.cc
This currently includes the following changes, enough to place the `DIFFINBUF` and `IBUFCTRL`
- falling back to all site types (and later on the default site type) when none match, needed because the `DIFFINBUF` is in a different site to the pad
- removing the search for 'special' intent wires only, as this doesn't apply to UltraScale+ and the iteration limit in the BFS search prevents a significant amount of general interconnect being searched in any case
- fixing the update of placed cells.
- skipping IO port pads in the dedicated interconnect check, as these are somewhat special with bidirectional wires and dealt with in `arch_pack_io`.
=> interchange: Support for UltraScale+ differential input buffers

common/placer_heap.cc, fpga_interchange/arch.cc, fpga_interchange/arch.h, fpga_interchange/arch_place_constr.cc, fpga_interchange/xdc.cc
This PR enables to LOC cells on BELs both from:
- attributes: `(* LOC="<site>", BEL="<bel>" *)`
- xdc: 
- `set_property LOC <site> [get_cells <cell>]`
- `set_property BEL <bel> [get_cells <cell>]`
Constraining a cell works only if both the LOC and BEL attributes are provided.
=> interchange: add user placement constraints handling

README.md, gowin/CMakeLists.txt
As far as I can tell this was only used while gradually porting from the generic target.
=> Remove python path from gowin target

ice40/pack.cc
=> ice40: Use default value when IP is missing BUS_ADDR74 parameter

common/idstringlist.h
This defines an empty `IdStringList` as being of size 1 containing an empty `IdString`, consistent with other uses of `IdStringList`. It should hopefully fix an occasional crash when clicking around in the GUI.
=> Fix definition of an empty IdStringList

CMakeLists.txt, gui/application.cc
Due to issues around static symbols, this is quite likely to produce a backtrace that only contains addresses. But at least this can be manually run through `addr2line` to get a more useful backtrace, it's better than nothing.
Backtraces are also currently implemented only on Linux only, because I don't have a Windows setup readily available.
cc @lethalbit
=> gui: Improve Fatal Error message

fpga_interchange/xdc.cc
Some XDC files may contain create_clock function. 
Right now we aren't using it and nextpnr fails on it.
This PR add dummy function to fix this issue
=> [Interchange] Add dummy function to parse creat_clock in XDC files

fpga_interchange/fpga_interchange.cpp
This was a harmless bug when cell names and types are always different, until you end up with an instance named after its type as LiteX tends to generate. This then means the cell name has been accidentally imported as an empty module, and then any instances of that type are replaced by nothing instead of becoming a leaf cell instance.
=> interchange: Don't attempt to import instances as modules

common/router2.cc
Otherwise, we might try and route through a LUT that happens to be the destination, causing a loop (this was sometimes breaking router2 on ice40 devices).
=> router2: Mark the destination as visited during backwards routing

common/arch_pybindings_shared.h, common/basectx.h, common/command.cc, common/context.h, common/nextpnr_types.h, common/pybindings.cc, common/report.cc, common/timing.cc, docs/report.md
This adds a JSON report containing basic utilisation and timing data for tracking and management in external tools that call nextpnr, to save them having to parse potentially unstable log output; as discussed in #786
=> Add JSON utilisation and timing report

gowin/arch.cc, gowin/pack.cc
Compatible with the current version of Apycula on constraints, of course the tri-state primitives will not be packed (yet), but in this case there is a message in gowin_pack about unsupported modes.
=> gowin: Add support for IOBUF and TBUF I/O modes. Change the constraint parser.

ecp5/bitstream.cc
When using the IO constraint on a differential output only the positive PIO site gets configured as open-drain.
```
IOBUF PORT "hdmi_clk_p" OPENDRAIN=ON;
```
If the iotype is a differential type then set the OPENDRAIN enum on complement PIO site.
=> ecp5: Enable OPENDRAIN on differential outputs

common/command.cc, common/router2.cc, common/timing.cc
This is an attempt to play with some of the ideas planned for longer-term router projects inside the existing framework of router2. 
In particular:
- bidirectional routing expansion
- improved re-use of existing routing for high-fanout nets
- reduced memory footprint
~~Unfortunately, although this does give a runtime speedup, it is currently hurting Fmax. Which means now is probably as good as a time as ever to investigate timing driven ripup/reroute.~~
~~Also, this is currently crashing and burning at the end of routing for Cyclone V for a reason that still needs to be investigated.~~
=> router2: Improved bidir routing and timing-driven ripup option

common/pybindings.cc
This is used by net.users for instance.
Removed by mistake in 4ac00af6fadc0405867fdac84229d2cda390c108
Fixes #799
=> pybindings: Fix mapping for PortRefVector

mistral/arch.cc, mistral/arch.h, mistral/bitstream.cc, mistral/lab.cc
Much of this is just mechanically replacing hardcoded `CycloneV::LAB`.
This reduces routing time for attosoc by quite a bit, presumably due to the ALMs being closer together.
=> mistral: Use MLABs as if they're LABs (for now)

.github/workflows/interchange_ci.yml, fpga_interchange/arch.h, fpga_interchange/chipdb.h, fpga_interchange/site_router.cc
This PR is to improve placement run-time, sacrificing placement density.
It appears in fact that quite some time is still spent when finding routing solutions within a site, and, with the presence of clusters (and specifically carry-chains), congestion within the sites has increased.
Clusters have a flag to indicate whether they are to be the only ones occupying a site.
Note: the site routing cache clear step is not required for this patch to work, but the problem I saw was that, in some runs when trying to place and route a LiteX design, the site router is not able to find a solution after clearing the cache. This seems quite odd, but I still need to investigate why the failure is happening.
=> interchange: place only cells belonging to the same clusters in the same site

fpga_interchange/xdc.cc
LiteX-based design come with XDCs that contain several commands which would through an error as not currently supported in the interchange.
This PR is to not throw a hard error on missing Tcl commands, but rather output a warning.
=> interchange: xdc: add common not_implemented function

gowin/arch.cc, gowin/arch.h, gowin/pack.cc, mistral/bitstream.cc
Added support for the INS_LOC instruction in the constraints file
(.CST), which is used to specify object placement.
Expanded treatment of IO_LOC/IO_PORT constraints, which now can
be applied to both ports and IO buffers.
Port constraints have priority.
Also allow the registers of the same type or pairs shown below to be
placed in the same slide:
```
|--------|--------|
| DFFS   | DFFR   |
| DFFSE  | DFFRE  |
| DFFP   | DFFC   |
| DFFPE  | DFFCE  |
| DFFNS  | DFFNR  |
| DFFNSE | DFFNRE |
| DFFNP  | DFFNC  |
| DFFNPE | DFFNCE |
```
=> gowin: Add constraints on primitive placement.

nexus/fasm.cc, nexus/pack.cc
This PR includes two major changes required for `IDDRX1` and `ODDRX1` plus tri-state control to work together on `LIFCL-17`:
- Fixed the case when `SIOLOGIC` is used ant `SEIOxx_CORE.T` connection is bypassing it
- Added inference and integration of flip-flops which drive `SEIOxx_CORE.T` into `SIOLOGIC` whenever possible
The first issue was causing a routing conflict as there are no separate routes for `SEIOxx_CORE.T` and `SIOLOGIC.TSDATA0` outside the tile. This is solved by detecting that `SEIOxx_CORE.T` bypasses `SIOLOGIC` and connecting `SIOLOGIC.TSDATA0`  to the same net. This does not affect the design operation as the mux on `SEIOxx_CORE.T` still choses the correct input making `SIOLOGIC.TOUT` ignored.
The second thing is an improvement which allows nextpnr to take advantage of …
=> nexus: Fixed an improved SIOLOGIC handling

common/placer1.cc, nexus/arch.cc, nexus/arch.h, nexus/archdefs.h, nexus/pack.cc
The spacing between PREADD9s and REG18s is sometimes uneven, and we need to take that into account when finding macro placements.
=> nexus: Fix DSP macro placement

.github/workflows/interchange_ci.yml, common/exclusive_state_groups.impl.h, common/placer1.cc, fpga_interchange/arch.h, fpga_interchange/arch_pack_clusters.cc, fpga_interchange/chipdb.h, fpga_interchange/macros.cc
This code adds cluster detection and placement for clusters created from macros.
So far only in-site macros are being placed, as out-site macros may could use global routing resources leading to visiting whole FPGA fabric.
This issue can be rectified be checking routing outside site if it's dedicated routing, like in BRAM64, carry chains or DIFF IO.
and only using them, and fail on routing that uses global routing.
Done so far:
=> Convert macros to clusters for better placement 

common/command.cc, common/context.h, common/nextpnr_types.h, common/report.cc, common/router1.cc, common/timing.cc, common/timing.h
In this PR I'm adding writing the final timing analysis report in the machine-readable JSON format. The report is attached to the current report JSON.
The included changes are:
=> Timing report in JSON format

.github/ci/build_interchange.sh, fpga_interchange/arch_pack_clusters.cc, fpga_interchange/dedicated_interconnect.cc
cc @mtdudek 
```
/home/gatecat/nextpnr/fpga_interchange/arch_pack_clusters.cc: In member function ‘void nextpnr_fpga_interchange::Arch::prepare_macro_cluster(const nextpnr_fpga_interchange::ClusterPOD*, uint32_t)’:
/home/gatecat/nextpnr/fpga_interchange/arch_pack_clusters.cc:681:39: warning: suggest parentheses around ‘&&’ within ‘||’ [-Wparentheses]
681 |                     if (node.idx != 0 && cell->name != ci->name || node.idx == 0 && cell->name == ci->name) {
|                         ~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~
/home/gatecat/nextpnr/fpga_interchange/arch_pack_clusters.cc:715:29: warning: loop variable ‘arc’ creates a copy from type ‘const std::pair<nextpnr_fpga_interchange::CellInfo*, nextpnr_fpga_interchange::pool<unsigned int> >’ [-Wrange-loop-construct]
715 | …
```
=> interchange: Enable Werror on CI and fix some compile warnings

.cirrus/Dockerfile.ubuntu20.04, gowin/arch.cc, gowin/arch.h, gowin/main.cc
Instead of parsing the partnumber with a regular expression, a simple table is used. This is done because the structure of the partnumber changes as new features appear (e.g., ES instead of C6/I5)
=> gowin: Add partnumbers and packages to the chipdb

common/command.cc
The method for randomisation initialisation used in nextpnr at present has been deprecated because of several extreme issues with it for some time now (for example, some implementations of rand() have near unchanging low bits, resulting in very predicable values).
This patch replaces that bad C code with modern C++11 `<random>` header based code.
=> common: Improved the random seed initialisation for the context

nexus/main.cc, nexus/pack.cc
This PR adds to the nexus architecture inference of directly connected LUT+FF pairs followed by clustering them together.
For each directly connected LUT and FF nextpnr now creates a new cluster. Moreover it glues FFs to existing clusters comprised of LUTs like wide LUTs and carry-chains.
The new behavior is enabled by default but can be disabled by the `--no-pack-lutff` option. Another option `--carry-lutff-ratio` allows to specify a ratio of clustering together FFs and LUTs which are part of carry-chains.
The added clustering approach has been analyzed on a single design (the SoC from https://chromium.googlesource.com/chromiumos/platform/hps-firmware) targeting LIFCL-17 FPGA using 500 chosen seeds. A timeout of 5min was set for each run so that when it expired a run was considered a …
=> nexus: LUT and FF clustering

.github/workflows/mistral_ci.yml, mistral/io.cc
=> mistral: DATAIN and DATAOUT of GPIO have swapped

common/router1.cc, ecp5/arch.cc, ecp5/arch.h, ecp5/archdefs.h
With these two changes I see a roughly 3x speedup in router1 time, ~550 seconds to 180 secs (on a i5-1145G7 laptop). The vector change is the main improvement.
I've been testing with a build of [microwatt for orangecrab](https://github.com/mkj/microwatt).
`nextpnr-ecp5 --json microwatt-placed.json --no-pack --no-place --lpf constraints/orange-crab-0.2.lpf --textcfg microwatt_out.config.tmp --85k --freq 48 --speed 8 --write microwatt-routed.json --timing-allow-fail --ignore-loops --package CSFBGA285 `
Input files
[microwatt-placed-bench.json](https://matt.ucc.asn.au/p/microwatt-placed-bench.json) 
[orange-crab-0.2.lpf](https://matt.ucc.asn.au/p/orange-crab-0.2.lpf)
([microwatt-bench.json](https://matt.ucc.asn.au/p/microwatt-bench.json) as input for pack and place)
=> Improvements to ecp5 router speed

ecp5/arch.h, ecp5/trellis_import.py
This reduces the final binary size by ~9 MB for 85k
=> ecp5: Reduce some chipdb fields from 32 to 16 bit

.cirrus/Dockerfile.ubuntu20.04, ecp5/arch.cc, ecp5/arch.h, ecp5/archdefs.h, ecp5/bitstream.cc, ecp5/main.cc, ecp5/pack.cc, ecp5/trellis_import.py
This enables the router to permute LUT inputs to improve routeability. Although this gets a big route time speedup on congested designs; it does seem to come with possible small Fmax cost on some low-congestion designs as the previous criticality-driven permute no longer takes effect (this could probably be fixed by having a router that was better at taking timing into account...)
Requires https://github.com/YosysHQ/prjtrellis/pull/181
=> ecp5: LUT permutation support

gowin/main.cc
For example, clearly distinguish between
GW1N-4
GW1NR-4
GW1NS-4
GW1NSR-4
GW1NSR-4
=> gowin: Recognize models correctly

README.md, machxo2/bitstream.cc, machxo2/examples/demo-vhdl.sh, machxo2/examples/demo.sh, machxo2/examples/mitertest.sh, machxo2/examples/simple.sh, machxo2/examples/simtest.sh, machxo2/main.cc, machxo2/pack.cc
This PR corrects the following bugs I found in the MachXO2 backend:
* Bitstream gen has more accurate logic to work around MachXO2's "wonderful" net naming scheme.
* `nextpnr-machxo2` will now error if the detected top-level I/O ports are not attached to a `FACADE_IO` `PAD` port.
* `--no-iobs` option was removed. It was always enabled, and it was a mistake to expose it in the first place.
* `mitertest.sh` can now handle JSON containing `FACADE_IO`. The script uses a flatten pass to instantiate tristate buffer modules and remove their `inout`s, which `write_smt2` doesn't support. 
* `uart.v` example now passes BMC w/ an SMT solver. I'm holding off on making it pass k-induction for now because I ran into a [snag](https://github.com/cr1901/yosys-experiments/tree/master/sat/dffhold) I'm not …
=> MachXO2 Checkpoint 2

nexus/arch.cc, nexus/arch.h
This uses a set of data structures based on #867 to speed up the nexus router1 runtime
cc @tcal-x; as you are using router1 for congested designs the runtime speedup from this might be of interest to you
=> nexus: router1 speedup based on #867

common/arch_api.h, common/context.cc, common/context.h, common/nextpnr_namespaces.h, common/place_common.cc, common/placer1.cc, common/timing.cc, common/timing_opt.cc, docs/archapi.md, docs/coding.md, ecp5/arch.cc, ecp5/arch.h, fpga_interchange/arch.cc, fpga_interchange/arch.h, generic/arch.cc, generic/arch.h, gowin/arch.cc, gowin/arch.h, ice40/arch.h, ice40/delay.cc, machxo2/arch.cc, machxo2/arch.h, mistral/arch.h, mistral/delay.cc, nexus/arch.cc, nexus/arch.h
🚨 BREAKING ARCHAPI CHANGE 🚨
This makes predictDelay be based on an arbitrary belpin pair rather than a arc of a net based on cell placement. This way 'what-if' decisions can be evaluated without actually changing placement; potentially useful for parallel placement.
A new helper predictArcDelay behaves like the old predictDelay to minimise the impact on existing passes.
=> archapi: Use arbitrary rather than actual placement in predictDelay [breaking change]

nexus/constids.inc, nexus/fasm.cc, nexus/pdc.cc
This PR adds possibility to provide `SLEWRATE` for nexus in PDC. This can be done with e.g:
```
ldc_set_port -iobuf {SLEWRATE=FAST} [get_ports my_awesome_port]
```
If not provided, the value is set to `MED`
=> nexus: handle SLEWRATE in pdc

gowin/arch.cc, gowin/cells.cc, gowin/constids.inc, gowin/pack.cc
Some models have I/O cells that are IOBUFs, and other types (IBUFs and
OBUFs) are obtained by feeding 1 or 0 to the OEN input.  This is done
with general-purpose routing so it's best to do it here to avoid
conflicts.
For this purpose, in the new bases, these special cells are of type IOBS
(IOB Simplified).
The proposed changes are compatible with bases of previous versions of
Apycula and do not require changing .CST constraint files.
=> gowin: Add simplified IO cells processing

gowin/arch.h
gridDimX and gridDimY are not initialized explicitly, which leads to
effects when the design is reloaded, say, from the GUI.
=> gowin: Initializing the grid dimensions

common/pywrappers.h, docs/generic.md, generic/arch.cc, generic/arch.h, generic/arch_pybindings.cc, generic/arch_pybindings.h, generic/archdefs.h, generic/examples/write_fasm.py
This won't affect Python-built arches significantly; but will be useful for the future 'viaduct' functionality where generic routing graphs can be built on the C++ side; too.
In particular; the number of hash table lookups during PnR are vastly reduced by using linear indices into `vector`s instead of `IdStringList`s looked up in `dict`s.
=> generic: Refactor for faster performance

common/sso_array.h
This prevents the implicit implementations of these from biting; in the case of heap-mode SSOArrays...
=> SSOArray: Implement move and assignment operators

gowin/arch.cc
In fact, there is also an input/output column.
=> gowin: Fix last MUX2_LUT8

common/hashlib.h
This PR changes the hashing function used for two integers from DJB2 to Cantor. The DJB2 one is meant for string characters and yields in quite high number of collisions for integers of values outside ASCII range. Cantor guarantees hash uniqueness.
Despite being more computationally complex the Cantor function boosts the performance which can be seen especially in router2 runtime on the nexus architecture. For the `hps_accel` design in `slim+cfu` configuration from the CFU Playground (https://github.com/google/CFU-Playground) its runtime dropped from `50s` to about `33.5s` (this may vary on different machines):
Routing times from 3 runs for DBJ2 and Cantor hashing:
router2:
| DJB2  | Cantor |
| ------------- | ------------- |
| 49.86s | 33.63s |
| 49.99s | 33.54s |
| 49.91s | 33.71s | …
=> Better hashing function for integer pairs

nexus/pack.cc
This PR removes the `MULT36_CORE` bel from DSP clusters created to implement the `MULTADDSUB9X9WIDE` macro as apparently it is not needed.
I couldn't find anywhere in the vendor docs which parts of sysDSP are actually required to implement this macro but from its description it certainly shouldn't require the mult36x36 core.
The fix has been tested on the HPS design from CFU playground in which a total of 8 of `MULTADDSUB9X9WIDE` for `LIFCL-17` is instanced. The final bitstream worked correctly in hardware proving that this fix is sound.
Apart from that I have run the same design through Radiant. It did fail on "mapping" as it run out of other DSP components but it didn't report that there is a need for 8 mult36x36. Besides that, LIFCL-17 has only 6 of those.
=> Fix for Nexus DSP packing

nexus/pack.cc
This PR adds honoring of the +/- 15% tolerance of `OSCA` output frequency for auto-generated clock constraints.
=> Honor nexus OSCA frequency tolerance

nexus/arch.cc, nexus/arch.h, nexus/main.cc
(edited)
This PR adds the a runtime parameter to control the multiplication factor of the estimate delay for nexus devices, without changing the default behaviour.
@gatecat cc
=> nexus: arch: add option to adjust the estimation delay multiplication factor

gowin/gfx.cc
By mistake, an empty decal gets filled with graphical elements.
=> gowin: Speed up the GUI

generic/arch_pybindings.cc, generic/arch_pybindings.h
This fixes `getPipsDownhill` and `getPipsUphill` in the generic python API.
=> generic: Add missing Pip vector binding

.cirrus/Dockerfile.ubuntu20.04, gowin/CMakeLists.txt, gowin/main.cc
This supersedes and includes #898 rebased on top of master
=> Add support for GW1N-9C and --family argument

nexus/pack.cc
The current version of Crosslink-NX Family Data Sheet lists the high
frequency oscillator maximum frequency as 481.5MHz (that is, 7% higher
than its nominal 450MHz):
https://www.latticesemi.com/-/media/LatticeSemi/Documents/DataSheets/CrossLink/FPGA-DS-02049-1-2-1-CrossLink-NX-Family.ashx?document_id=52780
Older documents listed a wider frequency range but ±7% is the range for
production parts.
I confirmed with Lattice that ±7% is the correct number. In this PR I haven't tried to tackle the question of pre-production parts. Lattice doesn't disclose anything publicly that I can find about the existence or performance of pre-production parts (no surprise there). It might be okay to just assume that if someone has such a part, they know that the tolerance was previously documented as 10%, …
=> nexus: reduce OSCA worst case to 7%

common/basectx.cc, common/design_utils.cc, common/nextpnr_types.h, ecp5/cells.cc, ecp5/globals.cc, ecp5/pack.cc, fpga_interchange/pseudo_pip_model.cc, fpga_interchange/site_arch.cc, generic/cells.cc, generic/pack.cc, gowin/cells.cc, gowin/pack.cc, ice40/bitstream.cc, ice40/cells.cc, ice40/chains.cc, ice40/pack.cc, machxo2/cells.cc, machxo2/pack.cc
This is part one of a potentially large and breaking netlist refactor.
It adds new, mandatory `NetInfo` and `CellInfo` constructors and starts to clean up older code constructing these objects in various ways to be more consistent.
It also adds a `Context` backreference to cells which will become of use in future steps when `design_util` functions are moved to being cell member functions.
=> refactor: New NetInfo and CellInfo constructors

.cirrus/Dockerfile.ubuntu20.04, gowin/CMakeLists.txt
Adds support for GW1NZ-1 chip that's found in the Tang Nano 1K development board.
~~Depends on https://github.com/YosysHQ/apicula/pull/81~~ (merged)
=> gowin: Add GW1NZ-1 support

gowin/constids.inc, gowin/pack.cc
The new primitive appears as an amalgamation of two existing OBUF
primitives.  Compatible with older versions of apicula, although, of
course, using TLVDS_OBUF with old databases will not bring the desired
result, but no crash.
=> gowin: Add support for true differential output

gowin/main.cc
The model should be recognized by the partnumber, --family is needed
only if the same partnumbers belong to different models.
This is done in order to automatically generate parameters for calling
nextpnr from Gowin files without problems: there also only partnumber is
used and only in some cases the model is specified with the -name
parameter and GW1NZ-1 is not such a case.
=> gowin: recognize partnumbers of GW1NZ-1

common/command.cc, common/parallel_refine.cc, common/parallel_refine.h, common/placer_heap.cc, common/placer_heap.h
This is currently very similar to the existing SA refinement pass; but partitions the placement area up and passes partitions to different threads.
Although there's an attempt to mitigate the lack of cross-partition-boundary optimisations by permuting the partitioning every outer loop iteration; that's not quite there yet and currently this carries a ~2-5% Fmax cost (in exchange for a ~2x speedup for this particular step of placement).
As this isn't Fmax-neutral yet, it's currently going to be a non default feature. But hopefully with some further investigation and development it should be possible to get at least as much QoR as the old SA path, both by finding better mitigations for the "boundary problem" and finding other, unrelated ways to improve performance (particularly those that …
=> parallel_refine: New, parallelised placement refinement pass

fpga_interchange/arch.cc, fpga_interchange/arch.h, fpga_interchange/site_lut_mapping_cache.cc, fpga_interchange/site_lut_mapping_cache.h
This PR removes some hardcoded values which cause failures when using larger devices such as US+ which have double the count of lut cells placeable in a site.
=> interchange: lut map cache: remove hardcoded values

nexus/pack.cc
This commit solves implicit cascading when clock signal drives DCC and logic
=> nexus: DCCs cannot be cascaded

fpga_interchange/globals.cc
This reference can become invalid after modifying the dict at line 109, because the dict implementation may reallocate it. Copy by value instead to ensure the validity of visit data.
=> [fpga_interchange] FIX: Don't hold reference to current visit in route_global_arc

gowin/arch.cc, gowin/cells.cc, gowin/constids.inc, gowin/pack.cc
GSR is added automatically if it was not instantiated by the user explicitly.
Compatible with old apicula bases, the functionality does not work, but
the crash does not happen --- just a warning.
=> gowin: Add the Global Set/Reset primitive

ecp5/bitstream.cc
Currently, if you specify a `DCUA` parameter as a hex string, e.g. `.CH0_UDF_COMMA_B("0x17c")`, any lowercase characters in it will be silently treated the same as `F`.
=> ecp5: accept lowercase characters in hex strings

mistral/bitstream.cc, mistral/constids.inc
Maybe there are cleaner ways of doing this, but this works fine*.
\* Sometimes. That needs to be investigated.
=> mistral: M10K initialisation support

gui/gowin/mainwindow.cc
GUI. Temporarily disable the button until the cause of the random crash is found.
=> gowin: BUGFIX temporarily disable the budget

nexus/arch.cc, nexus/fasm.cc
Added FASM feature emission for `DCC` and port timing class info. There is no point in adding `DCC` propagation delay to `getCellDelay` as the timing fuzzer from `prjoxide` reports it to be 0.
The added FASM feature emission has been successfully tested on hardware (LIFCL-40) where a `DCC` was used as a clock gate.
=> nexus: DCC support fixups

common/command.cc, gowin/main.cc
Specifically, those locales where the fractional part separator in
floating point numbers is not a period.
=> gowin: support for locales other than en_US and C

common/command.cc
The wire numbers are very large and it is undesirable to use a thousand
separator there. This is a side effect of enabling locale.
=> BUGFIX: disable the thousands separator

gowin/arch.cc, gowin/cells.cc, gowin/constids.inc, gowin/pack.cc
Gowin has a VCC and VSS input to almost every pip, which so far we've not been using, relying instead of a special LUT that's routed to all the VCC/VSS pins.
This PR adds a virtual VCC/GND bel that can contain the corresponding vendor primitive, and then sets up the pips correctly.
The constant packing step is now a bit silly maybe? It basically removes the global vendor primitive and then adds a new one, just with a predictable name so that other things can connect to it. Maybe it would be more sensible to either rename or store the existing primitive, but "if it aint broke dont fix it" so I just changed the packing from SLICE to VCC/GND.
=> Gowin: use global VCC and VSS nets

gowin/arch.cc
Place arbitrary constants side by side to avoid conflicts.
=> gowin: Name the constants

nexus/arch.h, nexus/fasm.cc, nexus/pack.cc
This PR adds default parameters to PLL cell in nexus.
Without this change bitstream generated using prjoxide does not work.
=> Nexus: Fixed OSCA parameters, add pll default parameters

ice40/chipdb.py
`/` is used to split elements in IdStringLists, but we treat the wirename part as one element so it won't roundtrip string conversion correctly if it has a `/` in it...
=> ice40: Fix wirenames containing / which is the list separator

CMakeLists.txt
This fixes #803 by properly following the libraries for TBB. I have not been able to test this against anything other than macOS and Linux.
=> cmake: properly include TBB libraries.

common/place/detail_place_cfg.h, common/place/detail_place_core.cc, common/place/detail_place_core.h, common/place/parallel_refine.cc
Ideally this needs a bit more documenting (hopefully tomorrow), but the aim is to reduce the amount of code - in particular move checking and evaulation - that needs to be duplicated between different placers, even if they want to be multithreaded.
=> Move general parallel detail place code out of parallel_refine

fpga_interchange/arch.cc, fpga_interchange/luts.cc, fpga_interchange/luts.h, fpga_interchange/site_arch.cc, fpga_interchange/site_lut_mapping_cache.cc
This PR makes nextpnr use the preferred constant net for unused LUT inputs as specified in FPGA interchange device resources. In code the `VCC` pin mask is now replaced by a vector of `PinConnection` which stores how a particular pin should be tied.
=> [interchange] Tying unused LUT inputs according to architecture

CMakeLists.txt
f4dc678 implicitly raised the minimum CMake version from 3.5 to 3.13 (which introduced that CMake policy).
There was #778 raised about it, but this is the only complaint in the past year, which suggests that compatibility with Ubuntu 18.04 LTS isn't so important to people.
Hence, explicitly raise the minimum CMake version, rather than implicitly breaking.
=> Bump minimum CMake to 3.13

common/kernel/report.cc
Mixed domains between the start and other points in a net are perfectly expected around things like IO, which begin/end in a pseudo "async" domain.
Fixes #988
=> Don't assert on mixed domain paths in report

ice40/arch_place.cc
Also, add some `const`s so we can't make the same mistake again
=> ice40: Fix accidental creation of empty ports

common/kernel/arch_pybindings_shared.h, generic/arch_pybindings.cc
This reduces the duplication, and also makes sure generic gains a few bindings that were missed off as a result of it being a special-case before.
=> generic: Use arch_pybindings_shared

common/kernel/arch_pybindings_shared.h, common/kernel/basectx.cc, common/kernel/basectx.h, common/kernel/context.cc, common/kernel/context.h, common/kernel/nextpnr_types.cc, common/kernel/nextpnr_types.h, common/place/detail_place_core.cc, common/place/parallel_refine.cc, common/place/place_common.cc, common/place/placer1.cc, common/place/placer_heap.cc, common/route/router2.cc, docs/netlist.md, fpga_interchange/arch.h, generic/arch.cc
When implementing concepts such as partition pins or deliberately split nets, there's a need for something that looks like a cell (starts/ends routing with pins on nets, has timing data) but isn't mapped to a fixed bel in the architecture, but instead can have pin mappings defined at runtime.
The PseudoCell allows this by providing an alternate, virtual-function based API for such cells. When a cell has `pseudo_cell` used, instead of calling functions such as getBelPinWire, getBelLocation or getCellDelay in the Arch API; such data is provided by the cell itself, fully flexible at runtime regardless of arch, via methods on the `PseudoCell` implementation.
In the common use case RegionPlug will be the desired PseudoCell but the API gives flexibility for other options, too.
Supersedes #490, …
=> netlist: Add PseudoCell API

README.md, ecp5/CMakeLists.txt, fpga_interchange/examples/chipdb.cmake, fpga_interchange/examples/chipdb_xilinx.cmake, fpga_interchange/examples/tests.cmake, ice40/CMakeLists.txt, machxo2/CMakeLists.txt
ae8966040bc7f148958d4ac0b989e04059b6ba06 converted the top-level CMakeLists.txt to use the Python3 module rather than PythonInterp, but there are also uses of it - and the variables it defines - in subdirectories.
I haven't tested the Windows command in the README.
=> Use CMake's Python3 rather than PythonInterp in subdirs

common/kernel/nextpnr_types.h, common/route/router2.cc
get_togo_cost is used with parameters in different order than defined. Noticed error when using clang as compiler.
=> Router fix

gowin/arch.cc
When it really needed to distinguish between the chips, this
unforgivable error was discovered :)
=> gowin: BUGFIX. Really memorize the chip

common/route/router2.cc, ice40/arch.h
Congestion at the source can occur in any arch that chooses to provide LUT-route-through psuedo-pips, including iCE40. Although the reason router2 can't then resolve the congestion easily needs to be investigated longer term, at least this resolves the some cases of router2 getting totally stuck on some iCE40 designs.
It also makes me think more arches might want to see if LUT-through-pips are useful things in general...
=> router2: Reserve source wire, too; ice40 fixes

common/kernel/command.cc, common/kernel/timing.cc, common/kernel/timing.h, nexus/arch.cc
This PR is a proof of concept of doing cross-domain timing checks. In general case two clock domains are independent. However, if both clocks come from the same source their frequencies are equal and they differ just in phase (or delay). This can be used to do timing checks for cross-domain paths whenever they are related.
The implemented algorithm looks for a common driver for each clock pair. If one is found then those clocks are considered related and a delay difference from that driver to their nets is stored. The delay is then taken into account when doing timing checks. A check is performed for cross-domain path only if its clocks are related.
=> [WIP] Support cross-domain clock relations in timing analyser

ice40/archdefs.h
I noticed this during my work reimplementing nextpnr, and it seems to be dead and wrong, or at least dead. Either way I think this is what was intended unless anyone can correct me.
=> Correct Not Equal operator implementation in ice40

gowin/arch.cc
When using `nextpnr-gowin` with a constraints file that has windows line endings the CR character (ASCII 13) would be left in the string from std::getline and it would fail the regular expression as .* doesn't match newline characters.
This would cause none of the constraints to be loaded and would give a warning like the following:
```
Warning: Invalid constraint:
Warning: Invalid constraint: IO_LOC "clk" 35;
Warning: Invalid constraint: IO_LOC "rst" 77;
Warning: Invalid constraint: IO_LOC "led[0]" 86;
Warning: Invalid constraint: IO_LOC "led[1]" 85;
Warning: Invalid constraint: IO_LOC "led[2]" 84;
Warning: Invalid constraint: IO_LOC "led[3]" 83;
Warning: Invalid constraint: IO_LOC "led[4]" 82;
Warning: Invalid constraint: IO_LOC "led[5]" 81;
Warning: Invalid constraint: IO_LOC "led[6]" …
```
=> Support windows line endings in constraints for nextpnr-gowin

common/kernel/property.h
=> Fix "implicit copy constructor for 'Property' is deprecated"

gowin/pack.cc
The GW1N-1 and GW1NZ-1 have a similar PLL, but the board with the former chip is already very hard to buy, so let's experiment with a more affordable chip.
=> gowin: add support for a more common chip

gowin/arch.cc, gowin/pack.cc
When a single primitive occupies several cells, care must be taken when manipulating the parameters of that primitive: when creating cells, each cell must receive a copy of all the parameters and not modify them unnecessarily.  That is, if possible, it is better to make all parameter changes before dividing the primitive into cells.
=> gowin: BUGFIX: Correctly handle resets

ecp5/main.cc
Fix e.g. generating netlists after packing only for debugging
=> ecp5: Only write bitstream if --textcfg passed

gowin/arch.cc, gowin/gfx.cc, gowin/gfx.h
A large number of global variables are not suitable for WASM, so completely disable the graphics part where the main array of them is used.  For other architectures GUI is still possible.
=> gowin: fix build for wasm

common/kernel/command.cc, common/place/placer_heap.cc, common/place/placer_heap.h
The `iter` variable used to generate a timeout if no valid placement can be found for a cell may get reset in https://github.com/YosysHQ/nextpnr/blob/78926b31db6dbfb465e2585ce0050bf93cb3e35c/common/place/placer_heap.cc#L930 The design in https://github.com/YosysHQ/nextpnr/issues/1062 contains a cell where the radius and ripup radius increase to 90 and after that it seems to never find a bel which satisfies the contraints. But the `notempty` label is consistently hit every 909 iterations while searching, causing `iter` to become 0 before it will ever trigger the timeout. The process will happily run for hours without going anywhere.
I think there is a reason this variable gets reset so a separate total is added to track the total number iterations allowing the timeout to be triggered. Note …
=> Timeout when legal placement can't be found for cell

gowin/arch.cc, gowin/arch.h, gowin/globals.cc, gowin/globals.h, gowin/main.cc
The dedicated router for clock wires now understands not only the IO pins but also the rPLL outputs as clock sources.
This simple router sets an optimal route, so it is now the default router. It can be disabled with the --disable-globals command line flag if desired, but this is not recommended due to possible clock skew.
Still for GW1N-4C there is no good router for clock wires as there external quartz resonator is connected via PLL.
The calculation of delays has also been fixed.
=> gowin: bugfix and improved clock router

common/kernel/context.cc, common/kernel/context.h, common/kernel/sdf.cc
This returns a quad rise/fall min/max delay rather than the single max delay from getNetinfoRouteDelay
=> context: Add getNetinfoRouteDelayQuad

gowin/arch.cc, gowin/arch.h, gowin/cells.cc, gowin/cells.h, gowin/constids.inc, gowin/globals.cc, gowin/pack.cc
* both instances of the new PLLVR type are supported;
* primitive placement is optimized for the use of dedicated PLL clock pins;
* all 4 outputs of each primitive can use the clock nets (only 5 lines in total at the same time so far).
=> gowin: add a PLL primitive for the GW1NS-4 series

CMakeLists.txt
Eigen considers the EIGEN3_INCLUDE_DIRS and EIGEN3_DEFINITIONS variables to be deprecated and they will no longer be exported in the next release after 3.4.0:
https://gitlab.com/libeigen/eigen/-/commit/f2984cd0778dd0a1d7e74216d826eaff2bc6bfab
Use the IMPORTED target instead, which seems to be the preferred way of consuming third-party CMake libraries.
=> use eigen as an IMPORTED target in CMake

gowin/arch.cc, gowin/arch.h, gowin/cells.cc, gowin/cells.h, gowin/constids.inc, gowin/globals.cc, gowin/pack.cc
This chip is used in the Tangnano9k board.
* all parameters of the rPLL primitive are supported;
* all PLL outputs are treated as clock sources and optimized routing is applied to them;
* primitive rPLL on different chips has a completely different structure: for example in GW1N-1 it takes two cells, and in GW1NR-9C as many as four, despite this unification was carried out and different chips are processed by the same functions, but this led to the fact that you can not use the GW1N-1 PLL with the old apicula bases - will issue a warning and refuse to encode primitive. In other cases compatibility is supported.
* Cosmetic change: the usage report shows the rPLL names without any service bels.
* I use ctx->idf() on occasion, it's not a total redesign.
Signed-off-by: YRabbit …
=> gowin: Add PLL support for the GW1NR-9C chip

ice40/cells.cc
Previously if a port was declared as `output`, there would be two issues :
- In all cases, the pull up settings from the PCF wouldn't be applied, even if there was a `TBUF`
- If the port was bound to a constant net `x` or `z`, this would end up as PIN_TYPE `0110_01` ( `PIN_OUTPUT` ) with `D_OUT_0` no connection, which would result in the pin being actively driven.  ( And AFAICT it could be driven to either 0 or 1 depending on its position in the IO tile ? Although I have yet to reconfirm this ).
This fixes both of theses.
I'm marking this as Draft because I don't have access to hardware ATM to double check everything ... will do during the week, but still open for code review if anyone has comments.
=> ice40: Improve `output` handling vs pull-ups and undriven

ecp5/pack.cc, ice40/pack.cc
I added a TODO. If `modesel` is tied to `0` and certain modes are selected we can push through either of the clock constraints directly. I couldn't quickly see how I can do this by grepping the codebase.  
Fixes https://github.com/YosysHQ/nextpnr/issues/804
=> ecp5: Propagate clock constraints through DCSC

machxo2/arch_pybindings.cc
This is basically just a #1053 port for machxo2.
=> machxo2: Fix Python bindings for pip iterators

common/kernel/hashlib.h
The definitions for uint32_t, uint64_t report as undefined when compiling under GCC13. They were previously found by transitive includes, but this is not guaranteed to work, and GCC13 forced the issue.
=> Include <cstdint> in common/kernel/hashlib.h

CMakeLists.txt
Clang 11 is failing on `-Wno-format-truncation`.
=> CMake: check if warning flag is supported before use

common/kernel/command.cc, common/place/detail_place_core.cc, common/place/detail_place_core.h, common/place/parallel_refine.cc, common/place/placer_heap.cc
Previously it was always disabled on WebAssembly builds.
WASI [has threads now](https://bytecodealliance.org/articles/wasi-threads).
=> common: disable parallel refinement only without threads

CMakeLists.txt
Together with https://github.com/YosysHQ/nextpnr/pull/1111 this change makes it possible to build nextpnr with or without parallel refinement support depending on whether the platform has threads available (in case of WASI, you can have WASI with or without threads).
=> CMake: detect platform support for threads

gowin/arch.cc, gowin/pack.cc
Simple deserialization primitives are implemented for all supported boards.
Compatible with older apicula bases.
=> gowin: Add implementation of IDDR and IDDRC primitives

gowin/arch.cc, gowin/arch.h
If the port is in a different cell than the primitive, then use the alias mechanism. 
Considerably compact code for OSC as an example.
=> gowin: add a common mechanism for placing ports

mistral/arch.h, mistral/lab.cc
Carry mode is per-ALM rather than per-LUT. So when route-through LUTs were being added for FF access in ALMs in carry modes, those LUTs would actually function in adder mode rather than pure buffers, causing occasional failures with certain seeds of certain designs.
=> mistral: Don't allow route-through LUTs in carry-mode ALMs

common/kernel/arch_api.h, common/kernel/base_arch.h, common/kernel/context.cc, docs/archapi.md, fpga_interchange/arch.h
This should enable custom delay calculation as per #1155 without requiring the arch-specific `#ifdef` any more.
=> archapi: Add getArcDelayOverride

mistral/arch.cc, mistral/arch.h, mistral/bitstream.cc, mistral/delay.cc
There are a number of timing-related goodies in here:
- the Mistral analogue simulator is now used for (admittedly-slow) timing signoff; it usually finds a few megahertz.
- routing timings have been redone; the old timings turned out to be about 11% more pessimistic than necessary.
- `predictDelay` and `estimateDelay` have been fitted to a sample design; this also helps Fmax a bit.
- HeAP has a parameter tweaked to account for the asymmetry of the Cyclone V.
Is this production-grade? Not quite, but I'd like to believe we're getting a bit closer.
=> mistral: improve timing calculation

gowin/constids.inc, gowin/pack.cc
Adds missing TLVDS_IBUF/IOBUF/TBUF primitives, as well as all kinds of LVDS emulation primitives.
=> gowin: implement differential IO primitives

mistral/delay.cc
I decided to remove the base cost of the delay estimates to encourage the placer to put things closer together. It's now a pretty good congestion-free estimate of critical path now.
=> mistral: rework delay estimate

common/kernel/command.cc, common/route/router2.cc
I've been tinkering with r2 over the past few days, and I think I have a set of weights that reaches a much higher maximum frequency than the defaults, using `mistral`, anyway.
The idea is to have more, smaller-step iterations, in the hopes of better negotiation between wires, and at least empirically, this seems to work out.
=> router2 alternative weights

mistral/delay.cc
Mistral's analog simulator has no waveforms for the M10K, as far as I can tell, which causes an assert to fire. In the hope that this gets resolved eventually, fall back to guesswork if there is no waveform available.
=> mistral: fallback to guess if simulator has no waveform

mistral/bitstream.cc, mistral/pack.cc
Having fixed the bug related to 13x1-bit addressing, I figured I should also get around to implementing 8x40-bit addressing as well. While I was there, I did a bit of cleaning up of #1168, although I'm still not entirely happy with this.
Once #1168 is merged, I'll rebase this.
=> mistral: add 8x40-bit M10K addressing mode

gowin/pack.cc
Proposes a fix for #1173 
Instead of routing constant `1'b0` and `1'b1` nets to LUTs, the LUT configuration is modified such that any value at that input those pin leads to the same output.
I removed `is_lc(ctx, uc)` from the `if` statement, so all nets are routed explicitly in this case. Should we handle that case differently?
=> gowin: fixes default networks

common/route/router2.cc
Hopefully for the last time?
(Perhaps nextpnr needs a webassembly CI job or something.)
cc @whitequark @gatecat
=> router2: fix 8935c186 (again)

CODE_OF_CONDUCT
This PR adds the same code of conduct that is present in YosysHQ/yosys, as discussed with @gatecat
=> Added a code of conduct, which was taken from the YosysHQ/yosys repo

himbaechel/uarch/gowin/constids.inc, himbaechel/uarch/gowin/cst.cc, himbaechel/uarch/gowin/globals.cc, himbaechel/uarch/gowin/gowin.h, himbaechel/uarch/gowin/gowin_arch_gen.py, himbaechel/uarch/gowin/pack.cc
Now the clock router can place a buffer into the specified network, which divides the network into two parts: from the source to the buffer, routing occurs through any available PIPs, and after the buffer to the sink, only through a dedicated global clock network.
This is made specifically for the Tangnano20k where the external oscillator is soldered to a regular non-clock pin. But it can be used for other purposes, you just need to remember that the recipient must be a CLK input or output pin.
The port/network to set the buffer to is specified in the .CST file:
CLOCK_LOC "name" BUFG;
=> gowin: Himbaechel. Extend clock router

generic/viaduct/example/synth_viaduct_example.tcl, himbaechel/arch.cc, himbaechel/arch.h, himbaechel/archdefs.h, himbaechel/chipdb.h, himbaechel/himbaechel_dbgen/bba.py, himbaechel/himbaechel_dbgen/chip.py, himbaechel/main.cc, himbaechel/uarch/example/example_arch_gen.py
This currently WIP and will probably end up landing after #1184.
Remaining issues are adding support for setting node/wire timings in the Python API as well as pip timings; and adding more examples of how this structure could be used to implement different timing models - like configurable cell types, and the spectrum from simple fixed pip delays to fanout-dependent delays (without RC data) to a full RC model.
The RC model implementation is also currently incomplete, but should be good enough for a context where most of the delays are on the pips and it's used to implement a small fanout penalty.
=> himbaechel: Initial timing support

.github/ci/build_himbaechel.sh, common/kernel/command.cc, common/kernel/command.h, himbaechel/arch.cc, himbaechel/arch.h, himbaechel/arch_pybindings.cc, himbaechel/himbaechel_api.cc, himbaechel/himbaechel_api.h, himbaechel/main.cc, himbaechel/uarch/example/example.cc, himbaechel/uarch/gowin/CMakeLists.txt, himbaechel/uarch/gowin/gowin.cc
This is a step to improve the user experience of himbächel by automatically determining the device and chipdb.
chipdb discovery uses the same binary-relative share directory finding code as Yosys, so should hopefully be pretty robust.
uarches must now provide a function to claim a device name, if they claim it they will be used for a given device. They must then call a function during initialisation to specify the chipdb path (although this can be overridden for debugging), how they determine chipdb name from device name and other arguments (e.g. family for gowin) is up to the uarch.
@yrabbit, I'd really appreciate any feedback and comments on how the Gowin side is looking, the code was mostly taken from the old Gowin arch but do say if you have feedback or suggestions for changing this …
=> himbaechel: Add discovery of uarch and chipdb

himbaechel/uarch/gowin/CMakeLists.txt
Use himbaechel/gowin instead of himbaechel/gowin/gowin.
=> gowin: Himbaechel. Fix install path

himbaechel/uarch/gowin/gowin.cc
For GW2A-18 and GW1N-9 you need to specify the family in addition to partno.
=> gowin: Himbaechel. Specify the chip variant.

common/kernel/timing.cc, common/kernel/timing.h, common/kernel/timing_log.cc
Fixes the bug @Ravenslofty reported in https://github.com/YosysHQ/nextpnr/pull/1183#issuecomment-1732692287
Also fixes missing slack histogram printing which I noticed while debugging this.
=> TimingEngine: Fix argument order and slack histogram reporting

common/kernel/timing.cc, common/route/router1.cc, fpga_interchange/cost_map.cc
`std::numeric_limits<delay_t>::min()` returns the smallest number larger then 0 for `float` which broke the worst endpoint search for timing reporting for any arch that uses `delay_t = float` or ``delay_t = double`` 
I have found some other suspect spots in the code. @gatecat please go over them whether they are correct. (I'm commenting these in a new comment)
=> kernel/timing: use std::numeric_limits::lowest() instead of min()

3rdparty/imgui/examples/imgui_impl_win32.cpp, 3rdparty/imgui/examples/libs/gl3w/GL/gl3w.c, 3rdparty/imgui/examples/libs/gl3w/GL/glcorearb.h, 3rdparty/imgui/examples/libs/glfw/include/GLFW/glfw3native.h, 3rdparty/imgui/imgui.cpp, 3rdparty/oourafft/fftsg.cc, 3rdparty/oourafft/fftsg2d.cc, 3rdparty/pybind11/docs/advanced/cast/strings.rst, common/kernel/base_arch.h, common/kernel/command.cc, common/kernel/embed.cc, gui/application.cc
Closes #1229 
Adds `#NOMINMAX` to all includes of `windows.h` to prevent the min/max macros from causing problems.
Replaces `__MINGW32__` with `_WIN32` in `command.cc`
Moves prototypes out of functions and to the top of `fftsg.cc` and `fftsg2d.cc` to prevent linker errors.
=> Windows fixes

himbaechel/arch.cc, himbaechel/arch.h, himbaechel/chipdb.h, himbaechel/himbaechel_dbgen/chip.py
Some changes split out of my ongoing nextpnr-xilinx backport-to-himbaechel work:
- Significant speedup and memory footprint reduction in database generation with some evil tricks
- Adding a chipdb "schema" version number
- Adding extra data for PIPs
- Adding some helper functions for package pin lookup
@yrabbit if you have a chance can you check this breaks nothing on Gowin?
=> himbaechel: Generation speedup and improvements

common/place/placer_static.cc, ice40/arch.cc
Two different patches here:
- from reading the elfPlace paper, the density multiplier and the potential energy should both be vectors; it's not yet clear to me how to change the potential energy, but fixing the density multiplier is easy enough.
- I added an `IO` group to iCE40 so that `static` can place I/O pads when a design doesn't have them specified by PCFs.
=> static improvements

common/kernel/arch_api.h, common/kernel/base_arch.h, common/kernel/nextpnr_types.h, common/route/router1.cc, common/route/router2.cc, docs/archapi.md, himbaechel/arch.cc, himbaechel/arch.h, himbaechel/chipdb.h, himbaechel/himbaechel_dbgen/chip.py, himbaechel/himbaechel_helpers.cc, himbaechel/himbaechel_helpers.h, himbaechel/uarch/example/blinky.v, himbaechel/uarch/example/constids.inc, himbaechel/uarch/example/example.cc, himbaechel/uarch/example/example_arch_gen.py, nexus/arch.h, nexus/pack.cc
High-fanout dedicated global constant routing has been a weak spot in nextpnr, and a previous complexity in e.g. Xilinx support, where it necessitated complex virtual routing structures so the general routers could route them efficiently.
This removes all the arch complexity by allowing wires to be tagged as having a constant value, and therefore creates a simplified backwards routing problem for constants, allowing such wires to have multiple sources.
This should also solve some of the performance problems with router1 for nextpnr-nexus.
=> archapi: Add new API for global constant routing

common/route/router2.cc
As constant nets could start from many possible locations (e.g. every interconnect tile), the backwards estimate to some arbitrary location is largely meaningless in this mode, so just set it to zero so it doesn't cause problems.
Fixes the router2 performance issue raised in #1235.
=> router2: Don't use estimates for constant nets

machxo2/arch.cc
This puts the post-placement delay prediction in a band that matches the output Fmax a bit better. Though I only tuned this using one design, the figure only has to be roughly correct anyway.
=> machxo2: less pessimistic delay prediction

ecp5/pack.cc
Currently a segfault happens while packing FFs when the DI port is not specified. Leaving it unconnected is probably incorrect, but it shouldn't crash the placer. This can only happen when doing direct instantiation. Fix by adding a check.
=> ecp5: Don't segfault when DI port of TRELLIS_FF unconnected

fpga_interchange/arch.h
Hi folks,
This fixes a missing declaration for the fpga_interchange submodule.
The error was introduced in #1228 :
```
nextpnr/common/kernel/pybindings.cc: In function ‘nextpnr_fpga_interchange::Context* nextpnr_fpga_interchange::load_design_shim(std::string, ArchArgs)’:
BUILD/nextpnr/common/kernel/pybindings.cc:61:34: error: invalid new-expression of abstract class type ‘nextpnr_fpga_interchange::Context’
61 |     Context *d = new Context(args);
|                                  ^
In file included from BUILD/nextpnr/common/kernel/nextpnr.h:24,
from BUILD/nextpnr/common/kernel/pycontainers.h:29,
from BUILD/nextpnr/common/kernel/pybindings.h:30,
from BUILD/nextpnr/common/kernel/pybindings.cc:23:
BUILD/nextpnr/common/kernel/context.h:31:8: note:   because the following virtual functions …
```
=> Fix abstract class implementation for fpga_interchange

common/place/placer_static.cc
This does increase runtime a bit, but it improves HPWL and hopefully reduces the amount of chaos a bit by reducing the dependence on the initial random starting positions.
=> static: Reduce stddev of initial solution

common/place/placer_static.cc, common/place/placer_static.h, ice40/arch.cc
- for UP `static` throws an assert over `WARMBOOT` being too big, so it was shrunk a little.
- added DSP bel config (again, the width is set to be less than 1 due to it being too big otherwise).
- fix the IO spacer size to be the size of a cell.
- finally, the iCE40 has the LUT and FF packed together into an `ICESTORM_LC`, so the logic group offset needs to be changed.
=> static/ice40: bug fixes for ultraplus

common/place/place_common.cc, common/place/place_common.h, common/place/placer1.cc
Various APIs have changed over time and the updates to placer1 along the way weren't reflecting semantic changes in how validity checking works, meaning that sometimes either initial placement or constraint legalisation would get stuck in an endless or near-endless loop.
=> placer1: Fix various bitrot

rust/rust.cc
I introduced a few compiler warnings in #1260. Silence/fix them.
=> rust: silence warnings

common/kernel/base_arch.h, common/kernel/command.h, common/kernel/idstringlist.h, common/kernel/nextpnr_types.h, common/kernel/pycontainers.h, common/kernel/pywrappers.h, common/place/timing_opt.h, gui/treemodel.h, ice40/arch_pybindings.h, ice40/cells.h, rust/rust.cc
This PR seeks to address some of the sea of unused parameter warnings created when compiling with `-Wall -Wextra  -Wpedantic` on GCC, and the Rust FFI bindings warnings while improving const and reference correctness in this code.
Tested to the best of our abilities with the iCE40 backend.
=> Fix: misc warnings

common/kernel/nextpnr_types.cc
This has always been a design intent of nextpnr, and is now strictly required by #1260.
=> Add trivially copyable invariant for ID types

CMakeLists.txt, common/kernel/hashlib.h, gui/fpgaviewwidget.cc
I got a bit annoyed at the lack of C++17 in nextpnr, so here's a PR to upgrade the C++ standard, as well as a fix to hashlib to remove the deprecated `std::iterator` usage.
=> upgrade to C++17

README.md
Update the readme to specify C++17 as of #1268, and CMake 3.13 as of #989.
=> readme: update build prerequisites

rust/nextpnr/src/lib.rs, rust/rust.cc
I apologise for the code churn, but this will make it more pleasant to use, instead of fighting raw pointers everywhere.
- a mutex is added to guard manipulation of the architecture backend; this might get broken into finer-grained locking in the future, but it'll do for now.
- the big change is that the FFI function declarations take references instead of pointers, because pretty much all functions would choke on a null pointer anyway; this reduces the number of functions that clippy demands to be marked as `unsafe` as a helpful side-effect.
- while doing this, I decided to change the API of `netinfo_users_leak` a bit, because I'm reasonably sure `PortRef`s shouldn't be modified (and then changed `npnr_portref_cell` to reflect this).
- since `Nets` doesn't contain any raw pointers, I can …
=> Rust bindings cleanup

README.md
Going forward this should be the main Nextpnr arch that Apicula supports, it's already way ahead in supported primitives and devices.
=> Add documentation for Himbaechel Gowin uarch

himbaechel/uarch/gowin/constids.inc, himbaechel/uarch/gowin/globals.cc, himbaechel/uarch/gowin/gowin.cc, himbaechel/uarch/gowin/gowin_utils.h, himbaechel/uarch/gowin/pack.cc
The OCE signal in the SP(X)9B primitive is intended to control the built-in output register. The documentation states that this port is invalid when READ_MODE=0 is used. However, it has been experimentally established that you cannot simply apply VCC or GND to it and forget it
- the discrepancy between the signal on this port and the signal on the CE port leads to both skipping data reading and unnecessary reading after CE has switched to 0.
Here we force these ports to be connected to the network, except in the case where the user controls the OCE signal using non-constant signals.
Also:
* All PIPs for clock spines are made inaccessible to the common router - in general, using these routes for signals that have not been processed by a special globals router is fraught with effects that …
=> gowin: Himbaechel. Deal with SP BSRAM ports.

common/place/placer_static.cc
Not seeing much speedup (or even parallel CPU usage yet), but it's a starting point there.
=> static: Add a basic threadpool

himbaechel/uarch/gowin/pack.cc
This type setting is not needed here - the packer distinguishes memory features by the X9 attribute, which will be correct anyway.
=> gowin: Himbaechel. SPX9 BSRAM BUGFIX.

himbaechel/uarch/gowin/globals.cc
* Don't stop at the first bad "arc", but use the global network to the maximum.
* Report partial/full use of global wires for the network.
* In case of complete routing failure, releasing the source - this is actually a BUGFIX.
=> gowin: Himbaechel. Improve global router.

himbaechel/uarch/gowin/pack.cc
Semi-dual port BSRAM (in Gowin terminology) has the same feature as Single Port - the CE and OCE signals must be synchronized.
Such a sin has not yet been noticed for Dual Port.
=> gowin: Himbaechel. Handle SDP OCE

common/place/placer_static.cc, ecp5/arch.cc
A quick and non-scientific test shows about a 10% improvement over plain static on picorv32.
=> static: First pass at timing-driven placement

common/kernel/command.cc
Tweak the FreeBSD version of proc_self_dirname() to work on NetBSD and use it.
Resolves issue #1298.
=> Add NetBSD support.

rust/.gitignore
Noticed these appear for rust integration, and there are big number of files in rust/target so best to add it to .gitignore
=> Ignore compile artifacts in rust directory

bba/main.cc, common/kernel/command.cc
nextpnr does not compile with the newest boost version 1.85.0 because the header file "boost/filesystem/convenience.hpp" does not exist anymore (removed because of deprecation). See
https://www.boost.org/users/history/version_1_85_0.html
This pull request replaces convenience.hpp with the correct header file.
=> Fixed header files for boost 1.85.0

common/kernel/design_utils.cc
Makes  `print_utilisation` format nicely for larger FPGA
=> Format utlilisation for larger FPGA as well

common/kernel/command.cc, himbaechel/arch.cc, himbaechel/uarch/gowin/gowin.cc
The nextpnr directory was missing from the fallback shared directory on windows only causing the chip db to not be found when using nextpnr-himbaechel through OSS-Cad-suite
=> Fix path to shared fallback on windows

ice40/arch_pybindings.cc
It seems that the pip iterator types should not be declared `const` to allow mapping the retun type of  `ctx.getPipsDownhill(...` `ctx.getPipsUphill(..`  to python types.
Same as:
- 52b02f7377a1fc88a7e1678e57af803f4d1bcc0c
- 6ee3daf06a4f1d1f26c2bf9a328bff726e5a12ea
- bd525d3548df30b5e4831348fdad7fe5fd5180c2
=> ice40: Fix Python bindings for pip iterators

himbaechel/uarch/gowin/constids.inc, himbaechel/uarch/gowin/gowin.cc, himbaechel/uarch/gowin/gowin.h, himbaechel/uarch/gowin/gowin_arch_gen.py, himbaechel/uarch/gowin/gowin_utils.cc, himbaechel/uarch/gowin/gowin_utils.h, himbaechel/uarch/gowin/pack.cc
As the board on the GW1N-1 chip becomes a rarity, its replacement is the Tangnano1k board with the GW1NZ-1 chip. This chip has a unique mechanism for turning off power to important things such as OSC, PLL, etc.
Here we introduce a primitive that allows energy saving to be controlled dynamically.
We also bring the names of some functions to uniformity.
=> Gowin. Implement power saving primitive

himbaechel/himbaechel_api.h, himbaechel/main.cc
This enables  Himbaechel uarch to override and implement additional operations on already constructed context, like loading of generated bitstream back to nextpnr
=> Enable user to override setupArchContext in Himbaechel arch

himbaechel/uarch/gowin/pack.cc
For pROM(X9) primitives in images generated by Gowin IDE, there is an interesting recommunication of inputs depending on the data bit depth. For example, in some cases, a high logical level may be applied to the Write Enable input, which, let’s say, is not entirely usual for Read Only memory.
Here we will do similar manipulations.
In addition, several minor bug fixes are included:
- Fixed bit numbering for non-X9 series primitives.
- Fixed decoder generation for BLKSEL - do not assume unused inputs are connected to GND.
- Use default values for BSRAM parameters - don't assume their mandatory presence.
=> Gowin. Taking into account the features of ROM

himbaechel/uarch/gowin/gowin.cc
It was not taken into account that there are only 6 ALUs per cell. As a result, on complex designs where ALUs and LUT-based memory are involved and there are many LUTs (like in the RISCV emulator), there were sometimes false positives about placement conflicts.
=> Gowin. BUGFIX. Fix placement checks

himbaechel/uarch/xilinx/xilinx.cc
The device names for Zynq chips don't have a trailing `t`, for example `xc7z010` and not `xc7z020`.
This PR makes presence of the `t` optional in the regex.
=> Himbaechel xilinx : Fix regex to parse Zynq device names

nexus/arch.cc
While `nextpnr-nexus --list-devices` shows several LFD2NX parts, the check in `arch.cc` prevents them from being passed to `--device`.
This PR treats them as the same family as the LIFCL parts as is done in the database.
=> Nexus: Allow LFD2NX devices to be specified

himbaechel/uarch/gowin/gowin_arch_gen.py
Some Clocks PIPS were not created due to a check for the presence of a delay class, now all wires are attributed to the class so that there is no longer any need for this check.
=> Gowin. BUGFIX. Create all Clock Pips.

common/kernel/nextpnr_types.h, common/kernel/report.cc, common/kernel/timing.cc, common/kernel/timing.h, common/kernel/timing_log.cc
My plan is to first implement hold time violations report. This will happen in the next PR. This PR is only moving more things in the timing engine and the reporting to `DelayPair`. Once that is done I can use the `DelayPairs` to implement a hold time violation report.
After the hold time reports I will add false path min/max delay using the same mechanism. 
TODO:
=> timing: Move towards DelayPairs for timing analysis

common/route/router2.cc, python/plot_congestion_by_coordinate.py, python/plot_congestion_by_wiretype.py
Currently, router2 only tracks how many wires of each type have given levels of overuse ("congestion by wiretype"). This PR extends that to cover how many wires of each type are used at all ("utilisation by wiretype") and how many wires are used in each X/Y coordinate ("utilisation by coordinate"),
It may be a good idea to sum overuse by wiretype or coordinate, but it's a little unclear if this would be useful information yet.
=> router2: additional heatmap data

common/place/placer_heap.cc
Fixes #1371 (and another drive-by fix to the ripup code to prevent ripup of locked bels I spotted at the same time...)
=> heap: Fix ripup criterea

ice40/cells.cc
I spotted in #1379 an unexpected cross-clock path showing up that the hard IP clock pins had been missed and weren't being driven through the global buffer network.
Maybe this even fixes some (but not all, there are also design issues in them reproducible in icestorm/sim models) of the weird issues people have seen over these years with these IPs...
This does fix the crash in #1379, but there's also no reason that the cross-clock path should crash timing analysis, so there's still something there for @rowanG077 to look into too.
=> ice40: Fix missing clock pin types

common/kernel/timing_log.cc
Caused by the original code path only handling routing which always has a net. Now with the additional clock delay reporting a net is not always available depending on exactly where it came from. Which lead to a faulty lookup. 
Together with https://github.com/YosysHQ/nextpnr/pull/1380 fixes https://github.com/YosysHQ/nextpnr/issues/1379.
=> timing_log: Handle potentially missing net when reporting crit path

common/kernel/command.cc
Fixes the `rngstate` assignment for `DeterministicRNG` when the seed is passed as a parameter. Assigning a seed of zero should be avoided as it leads to a constant zero output that can cause infinite loops, e.g., https://github.com/YosysHQ/nextpnr/blob/7c459805f63c07c44f22e46fbd08734da2578db8/common/place/placer_static.cc#L380-L381
=> Fix RNG seed initialization when passed as a parameter

CMakeLists.txt
Fixes #1384 
This seems to be a very old workaround forcing it to use the old approach that hopefully isn't needed any more on any of the systems we support.
=> cmake: Use upstream BoostConfig.cmake instead of cmake's own

himbaechel/uarch/gowin/gowin.cc, himbaechel/uarch/gowin/gowin_arch_gen.py, himbaechel/uarch/gowin/gowin_utils.cc, himbaechel/uarch/gowin/gowin_utils.h, himbaechel/uarch/gowin/pack.cc
* Allow clusters to be created from FFs and LUTs;
* Immediately create pass-through LUTs from free LUTs adjacent to FF - at the same time ensure alternating use of LUT inputs;
* In case of constant networks, such pass-through LUTs are disconnected from networks altogether;
* Allow FF to be placed directly into SSRAM slides - this is useful when using synchronous reading.
=> Gowin. FFs placement.

common/kernel/arch_api.h, common/kernel/base_arch.h, common/route/router2.cc, docs/archapi.md, himbaechel/arch.h, himbaechel/himbaechel_api.cc, himbaechel/himbaechel_api.h, mistral/arch.h
Add expandBoundingBox method to main nextpnr API and Himbaechel API to be able to handle architectures and uarch that have different needs for expanding bound box.
Used oportunity to remove Mistral specifics in router2.cc and move it into architecture specific file.
=> Add expandBoundingBox method to API

common/kernel/nextpnr_types.h, common/kernel/pybindings.cc, frontend/frontend_base.h
Hi,
I did not find a way to retrieve attributes (assigned in the verilog) of hierarchical cells even though yosys preserves them in the json netlist.
This patch adds an "attrs" dictionary to the HierarchicalCell structure and expose it through the python bindings.
Those attributes are imported in the front end after the import of the submodule.
This last point I am not sure of and maybe I am not doing this correctly/efficietly.
I wanted to add this feature to mimic the behavior of Xilinx's LOC/RLOC attributes where, in a hierarchy, you can assign a relative location to primitive cells within a module and a global location for instances of this module.
=> Add attributes to the hierarchical cells

himbaechel/uarch/gowin/pack.cc
By examining the output of `nextpnr`, I see an `ALU` in mode 1 (`SUB`) is wired like this:
```
Verilog I0    I0
Verilog I1    I1
Verilog I3    I3
```
When parsed by `gowin_pack`, this would result in an `ALU` that computes `I0 - I3`.
This PR swaps ports `I1` and `I3` to produce the following (verified in `nextpnr` output):
```
Verilog I0    I0
Verilog I1    I3
Verilog I3    I1
```
This matches Apicula documentation, as well as `ADDSUB` ports.
Can't test on real hardware at the time (used my Tang Nano 1K and 20K on a project, haven't ordered replacement yet).
=> Fix gowin ALU SUB mode ports

common/kernel/command.cc, himbaechel/uarch/example/example.cc, himbaechel/uarch/gowin/gowin.cc, himbaechel/uarch/gowin/pack.cc, himbaechel/uarch/ng-ultra/ng_ultra.cc, himbaechel/uarch/xilinx/xilinx.cc
None of these fixes are critical, except for the one that adds missing `#include <map>`, without which Himbaechel is broken on libc++.
=> Various fixes for clang/libc++ build

himbaechel/uarch/gowin/gowin_arch_gen.py, himbaechel/uarch/gowin/pack.cc
Erroneously created wires for specific IOs on the underside of some chips.
Fixes https://github.com/YosysHQ/nextpnr/issues/1417
Also cosmetic edits.
=> Gowin. BUGFIX. Do not create missing wires.

himbaechel/family.cmake
E.g. selecting only Gowin instead of the default shrinks the resulting binary by ~30%.
Not sure exactly what the variables should be named, I did it by analogy with the main `ARCH` cache variable.
=> himbaechel: allow subsetting uarches

CMakeLists.txt, ecp5/CMakeLists.txt, himbaechel/uarch/gowin/CMakeLists.txt, ice40/CMakeLists.txt, machxo2/CMakeLists.txt
This is explicitly recommended by the FindPython module documentation and is required to avoid failed builds on some systems. See: https://cmake.org/cmake/help/latest/module/FindPython.html
See also https://github.com/YosysHQ/prjtrellis/pull/243.
=> Find all components of Python at the same time

gui/CMakeLists.txt
=> CMake: use imported target for pybind11 (in the GUI)

CMakeLists.txt, cmake/BBAsm.cmake, ecp5/CMakeLists.txt, gowin/CMakeLists.txt, himbaechel/CMakeLists.txt, himbaechel/uarch/example/CMakeLists.txt, himbaechel/uarch/gowin/CMakeLists.txt, himbaechel/uarch/ng-ultra/CMakeLists.txt, himbaechel/uarch/xilinx/CMakeLists.txt, ice40/CMakeLists.txt, machxo2/CMakeLists.txt, nexus/CMakeLists.txt
This is useful for certain cross-compilation workloads, and to cache rarely changing build products.
To use this functionality, build e.g. as follows:
cmake . -B build-export -DEXPORT_BBA_FILES=../bba-files -DARCH=all
cmake --build build-export -t nextpnr-all-bba
cmake . -B build-import -DIMPORT_BBA_FILES=../bba-files -DARCH=all
cmake --build build-import
=> CMake: add support for exporting and importing .bba files

CMakeLists.txt
In-tree builds pollute the source directory and make version control more difficult to use effectively.
See https://github.com/YosysHQ/nextpnr/pull/1422#issuecomment-2606815347 for prior discussion.
=> CMake: disallow in-tree builds

ecp5/CMakeLists.txt, gowin/CMakeLists.txt, himbaechel/uarch/gowin/CMakeLists.txt, ice40/CMakeLists.txt, machxo2/CMakeLists.txt, nexus/CMakeLists.txt
This one also includes small patch for machxo arch to properly build with GUI enabled
=> CMake: Add include guards when IMPORT_BBA_FILES is used

3rdparty/json11/json11.cpp
Under certain conditions (e.g., building on Fedora 42 using gcc-15.0.1), compilation fails with the following error:
"error: ‘uint8_t’ does not name a type"
Explicitly include `<cstdint>` to prevent that situation.
Also see https://github.com/YosysHQ/yosys/pull/4852 and https://bugzilla.redhat.com/show_bug.cgi?id=2340929
=> Fix undefined type error in 3rdparty/json11/json11.cpp

ecp5/pack.cc
In one case, Yosys generates a never-toggling flipflop with constant-1 `CE` and `CEMUX` set to `INV`. This is a bit odd, but nextpnr should still handle this case correctly.
=> ecp5: Fix constant and inverted CEMUX

CMakeLists.txt, himbaechel/CMakeLists.txt
Due to the way CMake-generated Makefiles evaluate dependencies, this calls the `.bba` generation custom command twice, which then fails as they both use the same `.bba.new` file as an output and one of them moves it first.
This broke builds using `make -j` but not builds using `make -j nextpnr-himbaechel-example`.
=> CMake: exclude *-bba and *-chipdb targets from `make all`

himbaechel/uarch/gowin/constids.inc, himbaechel/uarch/gowin/globals.cc, himbaechel/uarch/gowin/gowin.cc, himbaechel/uarch/gowin/gowin.h, himbaechel/uarch/gowin/gowin_arch_gen.py, himbaechel/uarch/gowin/pack.cc
Adds output (MIPI_OBUF and MIPI_OBUF_A) and input (MIPI_IBUF) primitives to allow the use of “real” MIPI (not emulation) ports capable of operating in both HS and LP modes.
=> Gowin. Implement MIPI IO.

frontend/frontend_base.h, frontend/json_frontend.cc
prjunnamed normalizes ports that are not present in the primitive to be all-x. On iCE40, this can cause a false placement conflict between `SB_IO` cells where one's clock input is `x` and another's is some other net.
I haven't tested every other architecture (nor do I have the means to) so I can't know for sure this change won't have some other fallout, but it seems pretty weird to treat an absent port differently from an all-x port so arguably that would be an architecture bug.
Alternatively an iCE40-specific workaround in `arch_place.cc` could be used.
=> frontend: don't connect a const net to ports connected to `x`

common/kernel/basectx.cc
prjunnamed does not emit a net alias for toplevel ports. This works fine for constraining IOs but breaks clock constraints. This commit expands clock constraint application code to look up net aliases first, ports second.
As far as I can tell there shouldn't be any issues from this for existing flows.
=> kernel: look up ports when applying clock constraints

bba/main.cc
When -Wnarrowing is enabled, compilation of generated chipdb*.bin.cc files produces a large number of messages:
"narrowing conversion of ... from ‘int’ to ‘const char’ [-Wnarrowing]"
Explicitly using uint8_t instead of char when referencing embedded chipdb arrays resolves these issues.
Suggested-by: @whitequark
Resolves issue https://github.com/YosysHQ/nextpnr/issues/1449
=> Prevent chipdb array type narrowing conversion issues

CMakeLists.txt
add_custom_target syntax does not support EXCLUDE_FROM_ALL, actually it is reveresed, you need to add ALL if you wish to add it to `all` target. 
Without this change you would get
```
make nextpnr-all-bba -j9
[ 20%] Generating chipdb-384.bba
[ 60%] Generating chipdb-1k.bba
[ 60%] Generating chipdb-8k.bba
[100%] Generating chipdb-u4k.bba
[100%] Generating chipdb-5k.bba
[100%] Built target nextpnr-ice40-bba
make[3]: EXCLUDE_FROM_ALL: No such file or directory
make[3]: *** [CMakeFiles/nextpnr-all-bba.dir/build.make:70: CMakeFiles/nextpnr-all-bba] Error 127
make[2]: *** [CMakeFiles/Makefile2:383: CMakeFiles/nextpnr-all-bba.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:390: CMakeFiles/nextpnr-all-bba.dir/rule] Error 2
```
=> CMake: add_custom_target does not require EXCLUDE_FROM_ALL

gowin/main.cc
Adds deprecation warining as requested in https://github.com/YosysHQ/nextpnr/pull/1318 
It has to be done as (f)printf since during that time logger is still not active and it is useful to add warning in that particular moment.
=> gowin: Add deprecation message for nextpnr-gowin

common/kernel/arch_api.h, common/kernel/base_arch.h, docs/archapi.md, himbaechel/arch.cc, himbaechel/arch.h, himbaechel/himbaechel_api.h
GateMate contains inverting switchbox pips, which needs to be handled specially (I suspect Cyclone V does too, but it's been a long while since I looked at that). As part of bringup for that family, add an architecture API function to detect if a pip inverts. 
Inverting pips between two wires are disambiguated from non-inverting for use by e.g. Python by having an `INV` string appended to the name.
=> Add arch API function for pip inversion

himbaechel/uarch/gowin/globals.cc, himbaechel/uarch/gowin/gowin.cc, himbaechel/uarch/gowin/gowin.h, himbaechel/uarch/gowin/gowin_arch_gen.py, himbaechel/uarch/gowin/gowin_utils.cc, himbaechel/uarch/gowin/gowin_utils.h
Adds the ability to use high-speed clock lines (together with CLKDIV2 type frequency dividers operating on them) as signals for the CLKIN and CLKFB inputs of the rPLL and PLLVR primitives (these cover the full range of supported Gowin chips).
=> Gowin. Add HCLK wires to PLL.

himbaechel/uarch/gowin/cst.cc, himbaechel/uarch/gowin/globals.cc
Prohibits the use of Dynamic Clock Selection PIPs for networks where no DCS is present.
=> Gowin. Fix non-DCS networks.

himbaechel/uarch/gowin/globals.cc
We use a temporary separate small network (typically 2 - 3 sinks) for routing from the segment network source to the segment gate. This fixes the rare but unpleasant case of self-intersection when a route to a gate is routed using PIPs after the gate, this is no longer allowed when using a separate small network.
=> Gowin. BUGFIX Use a separate net for segment gates

common/place/placer1.cc
Had to check both boundaries since lot of getBelByLocation implementations do not check at least one of them and it is possible to hit this case.
=> placer1: add sanity check for try_swap_chain

ecp5/pack.cc
Each PLL output in ECP5 can be bypassed, which turns it into a wire that passes through ICLK unmodified. When an outputs mux is set to REFCLK, disregard other PLL configuration and copy the input constraint over unchanged.
---
Came across this while adding docs for `OUTDIVIDER_MUX[ABCD]` to https://blog.dave.tf/post/ecp5-pll/ .
Since this is a slightly esoteric corner of ECP5 configuration, I checked the behavior of `OUTDIVIDER_MUXn = REFCLK` on my ulx3s board, by routing all the clocks to I/O and looking at them on the oscilloscope with various PLL configurations. From this I can confirm that setting the output mux to "REFCLK" bypasses the PLL entirely and outputs ICLK unchanged.
---
I believe the ECP5 and MachXO2 PLLs are related enough that the XO2 packer likely needs the same fix, but …
=> ecp5: fix frequency constraint on bypassed PLL outputs

himbaechel/uarch/gatemate/gatemate.cc
This change in formula was found mostly by trial and error, but it reduces the time taken for router1 to route 061-litex-serv by about half, which is good enough when a single run takes about 15 minutes.
=> gatemate: improve estimateDelay

himbaechel/uarch/gatemate/bitstream.cc, himbaechel/uarch/gatemate/pack.cc, himbaechel/uarch/gatemate/pack.h, himbaechel/uarch/gatemate/pack_bram.cc, himbaechel/uarch/gatemate/pack_clocking.cc, himbaechel/uarch/gatemate/pack_io.cc
This change propagates clock constraints for input ports as well making SDC files usable on this uarch.
Removed disconnecting global clock (even routing already exported fine as config only) since otherwise clock does not get covered by nextpnr timing analysis.
P.S. Also have run clangformat and that change is in due to that.
=> gatemate: propagate clock constraints on input ports

himbaechel/uarch/gowin/cst.cc, himbaechel/uarch/gowin/globals.cc, himbaechel/uarch/gowin/gowin.cc
A segment router replaces the source-to-sink connection by general-purpose PIPs with bus-branch segment network connections.
The problem arises when the source is connected to the sinks directly without switching as in the case of LUT->DFF, such wires should be left as is, which is what this PR does.
=> Gowin. BUGFIX. Fix routing of the FF inputs.

himbaechel/uarch/gatemate/gatemate.h, himbaechel/uarch/gatemate/pack_io.cc, himbaechel/uarch/gatemate/route_clock.cc
DDR I/O requires a route-through CPE to pass the clock in, but since it doesn't go through the CPE CLK port, it wasn't guaranteed that the clock would be routed by the clock router, leading to clock-skew problems in some designs.
Thus we pass the DDR nets from the packer to the clock router to ensure they get routed.
I also included a small cleanup patch just to make that section a little nicer.
=> gatemate: include DDR route-throughs in clock router

himbaechel/arch.cc
This means you can use a wire alias instead of needing to know the normalised name for the wire.
=> himbaechel: output normalised wire in getWireByName

himbaechel/uarch/gatemate/bitstream.cc, himbaechel/uarch/gatemate/pack_clocking.cc, himbaechel/uarch/gatemate/pack_io.cc
Apparently `clang` doesn't like VLAs that much, and neither do I or C++ in general (they are not in the language spec). Using vectors is not exactly identical but it should work the same.
After these changes, [`nextpnr-himbaechel` can be build for `darwin-arm64`](https://github.com/jmi2k/oss-cad-suite-build/actions/runs/16005189044).
Unfortunately, I don't own a device to test these changes (neither an Apple device nor a Gatemate FPGA) so these changes are not tested.
=> himbaechel: gatemate: replace VLA with C++ features

himbaechel/uarch/xilinx/CMakeLists.txt
This PR brings `himbaechel/uarch/xilinx/CMakeLists.txt` closer to its counterparts.
1. Replace hardcoded `/usr/bin/python3` with the more common `${Python3_EXECUTABLE}`, which can be set when calling `cmake`.
2. Recognize `IMPORT_BBA_FILES`, making it possible to use `.bba` files without setting `HIMBAECHEL_PRJXRAY_DB`.
3. Recognize "all" as a valid value for `HIMBAECHEL_XILINX_DEVICES`, defaulting to the list of devices that can be built from [f4pga/prjxray-db](https://github.com/f4pga/prjxray-db).
These changes were made while trying to enable support for Xilinx devices on a fork of `oss-cad-suite-build`. I've split them all in different commits to facilitate rejecting any of them separately, but I could also squash them together if that's desirable.
=> himbaechel: xilinx: misc `CMakeLists.txt` improvements

machxo2/bitstream.cc
When using nextpnr and trying to build a design that uses the pins that have I3C functionality, for example `LCMXO3D-9400HC-6SG72I`, I would get an error:
```
Terminate called after throwing an instance of 'nextpnr_machxo2::assertion_failure'
what():  Assertion failure: no tile at (0, 29) with type in set (/home/via/dev/nextpnr/machxo2/arch.h:1026)
Aborted
```
I get a similar error when using RPLL, and after debugging I saw that the GPLL_R0 location was close but didn't match. I'm assuming this is just a typo and the second PLL hasn't been tested, but I don't know much about these things and don't know if this fix is appropriate (or might break other machxo(2) chips)
=> machxo3d: minor fixes for I3C pins and RPLL

cmake/FindApycula.cmake
This item is likely no longer necessary, as this executable file has been unavailable since May, with the complete transition to Himbaechel.
=> Gowin. Remove search for old Apicula.

himbaechel/uarch/gatemate/gatemate.cc, himbaechel/uarch/gatemate/gatemate.h
Follow-up to #1527.
As an idle experiment, I also tried to quantify the effects of the `placeAllAtOnce = true` setting on performance, using the same experiment.
placeAllAtOnce | 0% | 25% | 50% | 75% | 100%
-- | -- | -- | -- | -- | --
TRUE | 18.19 | 22.8725 | 24.485 | 28.485 | 32.99
FALSE | 18.36 | 24.955 | 27.1 | 29.135 | 32.95
so I guess that's being turned off too. that leaves gatemate using the default heap configuration, so we can remove the override.
=> gatemate: don't place cells all at once

cmake/CheckCXXCompilerHashEmbed.cmake
Apple Clang++ 17.0.0 (Xcode build tool installed version for macOS 15.6) fails to compile nextpnr@master because clang++ treats hash embeds as signed data (even though the same version of clang handles the same exact file just fine). [Minimum example for behavior reproduction](https://github.com/Willmac16/macos-embed-bug) on the right clang version.
Here's the error I get when compiling against master:
```bash
/Users/wmac/orange/nextpnr/build/ecp5/chipdb-45k.bin.cc:5:1: error: constant expression evaluates to -96 which cannot be narrowed to type 'uint8_t' (aka 'unsigned char') [-Wc++11-narrowing]
5 | #embed "/Users/wmac/orange/nextpnr/build/ecp5/chipdb-45k.bin"
| ^
/Users/wmac/orange/nextpnr/build/ecp5/chipdb-45k.bin.cc:5:1: note: insert an explicit cast to silence this issue
5 | #embed …
```
=> Change Hash Embed check to check for erroneous signed #embed

himbaechel/arch.cc, himbaechel/arch.h, himbaechel/chipdb.h, himbaechel/himbaechel_api.cc, himbaechel/himbaechel_api.h, himbaechel/himbaechel_dbgen/chip.py
Add user ability to override:
```
bool getCellDelay(const CellInfo *cell, IdString fromPort, IdString toPort, DelayQuad &delay) const;
TimingPortClass getPortTimingClass(const CellInfo *cell, IdString port, int &clockInfoCount) const;
TimingClockingInfo getPortClockingInfo(const CellInfo *cell, IdString port, int index) const;
```
And also add SpeedGradePOD extra_data so we can store additional timing information per speed grade in chip database
=> himbaechel: Extend API to enable cell delay override

himbaechel/uarch/gowin/constids.inc, himbaechel/uarch/gowin/globals.cc, himbaechel/uarch/gowin/gowin_utils.cc
A programmable on-chip crystal oscillator has been implemented for the GW5A series.
A critical innovation in this series was the change in the nature of the OSC output pin—it now belongs to the clock wires, and therefore the routes must be made with a special global router, as there is no possibility of using routing through general-purpose PIPs.
At the same time, we are transferring the outputs of all previous generations of OSC to potential clock wires. At the moment, this will not affect the way they are routed - they will still end up as segments as before, but in the future we may optimize the mechanism.
=> Gowin. Implement on-chip oscillator.

himbaechel/uarch/gowin/globals.cc, himbaechel/uarch/gowin/gowin_arch_gen.py, himbaechel/uarch/gowin/gowin_utils.h
Very rarely (about once a year), the dedicated clock router would malfunction, issuing an incorrect route.
The reason turned out to be the so-called gate wires to the global clock wire system from the logic. Among the PIPs for which these wires are sinks, there are PIPs where the sources are also clock wires.
This leads to the possibility of feeding the clock signal back into the gate and again into the global clock MUX.
If handled carelessly, this can lead to a complete loop.
But the loop option itself is particularly useful in the case of DCS (dynamic clock selection) - the fact is that because these primitives have four clock inputs and each of them could theoretically address all 56 clock sources, but in practice there are not enough wires and the DCS inputs cannot serve as sinks for …
=> Gowin. BUGFIX. Add data about gate wires.

himbaechel/uarch/gatemate/bitstream.cc, himbaechel/uarch/gatemate/config.cc, himbaechel/uarch/gatemate/config.h, himbaechel/uarch/gatemate/delay.cc, himbaechel/uarch/gatemate/extra_data.h, himbaechel/uarch/gatemate/gatemate.cc, himbaechel/uarch/gatemate/gatemate.h, himbaechel/uarch/gatemate/gen/arch_gen.py, himbaechel/uarch/gatemate/pack_clocking.cc, himbaechel/uarch/gatemate/pack_cpe.cc, himbaechel/uarch/gatemate/pack_io.cc, himbaechel/uarch/gatemate/pack_mult.cc, himbaechel/uarch/gatemate/route_clock.cc
TODO: 
- split net that is actually used by CPE_BRIDGE and connect input and output pins, so we can use it for post pnr simulation.
- create separate PR for router2 changes
- bump required chipdb version
=> gatemate: use CPE bridge

himbaechel/uarch/gatemate/ccf.cc, himbaechel/uarch/gatemate/cells.cc, himbaechel/uarch/gatemate/constids.inc, himbaechel/uarch/gatemate/extra_data.h, himbaechel/uarch/gatemate/gatemate.cc, himbaechel/uarch/gatemate/gatemate.h, himbaechel/uarch/gatemate/gen/arch_gen.py, himbaechel/uarch/gatemate/pack.cc, himbaechel/uarch/gatemate/pack.h, himbaechel/uarch/gatemate/pack_bram.cc, himbaechel/uarch/gatemate/pack_clocking.cc, himbaechel/uarch/gatemate/pack_cpe.cc, himbaechel/uarch/gatemate/pack_io.cc, himbaechel/uarch/gatemate/pack_mult.cc, himbaechel/uarch/gatemate/tests/lut.cc, himbaechel/uarch/gatemate/tests/testing.cc, himbaechel/uarch/gatemate/tests/testing.h
This one search for better PLL/BUFG assignment when that is possible.
Currently limiting number to 4 PLLs and BUFGs independently of number of dies, this makes copy of all clocks possible, so they become available in all dies in same order, this makes use of A2 and A4 for lower clock number.
Also it fixes special case where CC_ODDR is having inverter on output, by moving that inverter to both inputs. 
Separate dies are now defined as regions, and cells can be assigned to be in desired one.  force_die option now sets region for all non-pre-placed cells to a given one. We are also making sure that pack procedure preserves region information ( for future use).
=> gatemate: cleanup of PLL and BUFG

himbaechel/uarch/gatemate/pack.cc, himbaechel/uarch/gatemate/pack.h
If BEL attribute is set and cell is part of cluster placer will crash. Prevent that for now until placer can handle this.
=> gatemate: respect keep attribute and prevent crash with BEL set

himbaechel/uarch/gowin/gowin.h, himbaechel/uarch/gowin/gowin_arch_gen.py, himbaechel/uarch/gowin/gowin_utils.cc, himbaechel/uarch/gowin/gowin_utils.h, himbaechel/uarch/gowin/pack.cc
In the new series of chips, the SemiDual Port primitive has one RESET pin instead of two in previous versions - RESETA and RESETB.
Physically, the two pins are still there and both must be connected, with RESETA being constant.
=> Gowin. GW5A series BSRAM fix.

ice40/tests/hx1k.cc, ice40/tests/hx8k.cc, ice40/tests/lp1k.cc, ice40/tests/lp384.cc, ice40/tests/lp8k.cc, ice40/tests/up5k.cc
If the chipdb is not found, the Setup() call throws, but GTest still calls TearDown, which then stumbles over the uninitialized pointer.
This makes the tests fail without valgrind errors or segfaults at least.
=> ice40: Initialize context pointer in tests
