- common/placer1.cc
Noticed in MSVC build. This is also potential fix for issue #3
> Removes unnecessary unlock causing trouble with placer

- ice40/pack.cc
Not seeing a particular improvement in Fmax or success rate, need to benchmark a bit more though
> ice40: Promote 'logic' globals as well as clock/enable/reset

- common/command.cc
- common/command.h
- common/project.cc
- common/project.h
- ecp5/arch.h
- ecp5/main.cc
- ecp5/project.cc
- generic/arch.cc
- generic/arch.h
- generic/main.cc
- generic/project.cc
- gui/basewindow.cc
- gui/basewindow.h
- gui/ecp5/mainwindow.cc
- gui/ecp5/mainwindow.h
- gui/generic/mainwindow.cc
- gui/ice40/mainwindow.cc
- gui/ice40/mainwindow.h
- ice40/arch.h
- ice40/main.cc
- ice40/pcf.cc
- ice40/project.cc
Keeping most of common part for handling command line handling and project handling common and implement arch specific parts. 
Waiting for settings to be implemented in order to finish project saving properly.
> Common main and project

- common/placer1.cc
- ice40/arch.h
- ice40/arch_place.cc
- ice40/chains.cc
A few low hanging optimisations to speed up the placer. On my machine down from 18K samples to 14K...
[design03.pdf](https://github.com/YosysHQ/nextpnr/files/2276516/design03.pdf)
> Placer speedup

- common/timing.cc
Checked on #65 testcase and picorv32
> Fix for min_slack == max_slack => bin_size == 0

- ice40/pack.cc
> ice40: Add error for bad PACKAGE_PIN connections

- ice40/pack.cc
Signed-off-by: Clifford Wolf <clifford@clifford.at>
> Add info message for promoted global nets

- ice40/pack.cc
> ice40: Fix disconnection of PACKAGEPIN for PAD PLLs

- common/router1.cc
> router1: Fix unrouted, undriven nets

- common/placer1.cc
- ice40/arch.h
- ice40/arch_place.cc
- ice40/pack.cc
Fixes #148 
@swetland If you could confirm that :)
> Fixes for global promotion

- ice40/pack.cc
Fixes #141 
It also tries to provide more meaningful error messages for various errors that can be in the design.
> ice40: Complete rework of the way PLLs are placed and validity checks

- ice40/bitstream.cc
* Instead of "patching" input_en, we completely separate config for
normal and LVDS pair.
- For normal pair, nothing changes
- For LVDS pairs, the IE/REN bits are always set as if the input buffer
are disabled. Then if input_en was set to 1 (i.e. the input is
actually for something), then we set the IoCtrl.LVDS bit.
- Also for LVDS, if input is used, pullups are forcibly disabled.
* When scanning for unused IOs, never process those part of a LVDS pair.
They will have been configured by the complement
> ice40: Update the way LVDS inputs are handled during bitstream generation

- ice40/pack.cc
Useful when nextpnr promotes something to a global and breaks timing again.
> ice40: print fanout of nets promoted to globals

- ecp5/globals.cc
- ecp5/pack.cc
> ecp5: Pre-place PLLs and use dedicated routes into globals

- ice40/arch.cc
- ice40/bitstream.cc
- ice40/cells.cc
- ice40/cells.h
- ice40/pack.cc
Signed-off-by: Daniel Serpell <daniel.serpell@gmail.com>
> ice40: Add support for placing SB_LEDDA_IP block.

- gui/application.cc
See http://doc.qt.io/qt-5/qabstractopenglfunctions.html
> Fix crash starting the GUI on macOS where we must request a core profile

- common/timing_opt.cc
Signed-off-by: David Shah <davey1576@gmail.com>
> timing_opt: Fix generic build

- common/timing.cc
Thanks @smunaut for reporting!
> timing: Fix critical path print

- common/chain_utils.h
> common/chain_utils: Don't allow overlapping chains

- ice40/pack.cc
> ice40: Fix LOCK feedthrough insertion with carry or >8 LUTs

- ice40/arch.cc
> ice40: Add budget override for CO->I3 path

- ice40/pack.cc
Fixes error building testcase from #145
> ice40: PLLs can't conflict with themselves

- common/timing.cc
> [timing] Fix off-by-one error

- .cirrus.yml
Created to ensure it  runs on CI
> tests: Bump submodule to include ecp5 regressions

- gui/designwidget.cc
Signed-off-by: Marcin Kościelnicki <marcin@symbioticeda.com>
> gui: Fix Cells/Nets tab contents.

- common/placer1.cc
- json/jsonparse.cc
> json: Fix inputs directly driving inouts

- ice40/arch.cc
- ice40/bitstream.cc
- ice40/cells.cc
- ice40/cells.h
- ice40/pack.cc
> ice40: Add support for SB_I2C and SB_SPI

- ice40/arch.cc
- ice40/arch_place.cc
> SB IO conflict checks

- common/design_utils.cc
- common/design_utils.h
- ecp5/pack.cc
> ecp5: Fix USRMCLK primitive

- ice40/pack.cc
> ice40: Add support for HFOSC trimming

- ecp5/family.cmake
This is the matching pull request for https://github.com/SymbiFlow/prjtrellis/pull/72 to fix building on OS X.
> Use cmake's find_library to search for pytrellis.

- gui/application.cc
- gui/fpgaviewwidget.cc
- gui/lineshader.h
* Fix line shader when running under the core profile and make version match those elsewhere.
* Make surface format version match the openGL functions we are using.
> Fix device view not showing anything on macOS.

- json/jsonparse.cc
1. Ports are already used in PCF and LPF files, so it is natural
that the developer would use them for constraints as well.
(Actually I think currently the LPF FREQUENCY PORT constraint
doesn't work correctly.)
2. Unpredictable (the set of netlabels nextpnr looks at depends on
the optimizations during synthesis) net naming makes it impossible
for code generators like nMigen to reliably apply clock constraints.
Fixes #280.
> When choosing between labels for one net, always prefer ports

- json/jsonparse.cc
Depends on : https://github.com/YosysHQ/yosys/pull/1124
> Add support for upto and offset in JSON files

- bba/main.cc
Signed-off-by: Marcin Kościelnicki <marcin@symbioticeda.com>
> bba: Fix str with empty string.

- common/nextpnr.cc
- common/timing.cc
- ecp5/arch.cc
- ecp5/arch_place.cc
- ecp5/bitstream.cc
- ecp5/cells.cc
- ecp5/globals.cc
- ecp5/main.cc
- ecp5/pack.cc
- json/jsonparse.cc
- json/jsonwrite.cc
This allows the building of a "hard macro" part of a design.
> Add out-of-context mode to ECP5 architecture

- ice40/main.cc
> ice40: Only warn about default package if there is no package argument

- ecp5/bitstream.cc
- ecp5/globals.cc
> ecp5: Add support for clock gating with DCCA

- ecp5/pack.cc
- ice40/pack.cc
> Move clock constraints across buffers in more cases

- ice40/chains.cc
> ice40: Fix carry feed-out when we have to split the chain next

- ecp5/arch.cc
- ecp5/archdefs.h
- ecp5/bitstream.cc
- ecp5/pack.cc
> ecp5: Adding support for 36-bit wide PDP RAMs

- common/router1.cc
- ecp5/globals.cc
- frontend/frontend_base.h
- generic/pack.cc
- Load net attributes in frontend
- router1 to keep existing routing intact
> Fixes for partial reconfig demo

- common/arch_pybindings_shared.h
- common/command.cc
- common/nextpnr.h
- common/svg.cc
- python/svg_placement.py
- python/svg_routing.py
- python/svg_routing_fast.py
Adds option to write an SVG file of graphics after placement or routing (latter is massive, finding stuff that actually opens it is a bit of a challenge).
> svg: Basic SVG graphics rendering

- README.md
see https://github.com/YosysHQ/nextpnr/pull/404 and https://github.com/SymbiFlow/prjtrellis/pull/123
> Update README with TRELLIS_INSTALL_PREFIX example

- ecp5/cells.cc
- ice40/cells.cc
Previously, unused inout bits would end up as outputs driving their default value. This changes the behaviour to those bits being inputs, i.e. high-impedance, which should reduce user surprise. See also YosysHQ/yosys#1721
cc @emard
> Improve handling of unused inout port bits

- ecp5/arch.cc
- ecp5/arch.h
- ecp5/bitstream.cc
- ecp5/main.cc
Also need SymbiFlow/prjtrellis#127 for bitstream generation.
Fixes #409 
@awygle please can you test this and report back, as I don't actually have any '12k' hardware?
> ecp5: Proper support for '12k' device

- common/command.cc
It's not that important but decided to do a PR.
> command.cc: Use correct constant for default router

- ecp5/globals.cc
- ecp5/lpf.cc
- ecp5/pack.cc
Gets #438 to the build stage, at least.
> Fixes for the Lattice SERDES eye demo designs

- gui/ice40/mainwindow.cc
- ice40/arch.cc
- ice40/arch.h
- ice40/main.cc
Support Lattice HX4K  directly, old way  (over HX8K) still supported without change.
> Support 4K parts directly

- common/pybindings.cc
> Made proper exception translation

- common/nextpnr.cc
- ecp5/pack.cc
> Hierarchical floorplanning fixes

- common/timing.cc
Also add an error message that makes debugging/triaging a bit easier.
cc @awygle
> timing: Fix counting of fanin in out-of-context mode

- README.md
I found these while scrolling through
> README.md: Fix two typos

- docs/constraints.md
- ecp5/docs/primitives.md
This is a first attempt to add some short information about each supported primitive to tell people what it is doing. I think this could be useful for beginners like me or people that are not yet familiar with the Lattice-stuff.
I am sorry this pull-request contains my first pull-request too, beginners make mistakes... I will try to fix this. Feel free to edit/delete. Submitting this as a draft first.
edit: Seems like i cannot fix it. I apologize. Please tell me what to do, feel free to edit/delete/discard/...
> ECP5: annotate supported primitives

- common/router2.cc
Sets up per-thread RNG and bounding boxes, to prevent race conditions between threads resulting in non-deterministic behaviour between runs.
> router2: Improve thread safety

- common/router2.cc
This gets more predictable timing, and an overall increase of about 5-10%, when using router2
> router2: Avoid ripup of critical path

- ice40/pack.cc
This also refactors PLL packing into its own function, so that oscillators can be packed and auto-constrained first, then an oscillator driving a PLL will derive constraints correctly.
> ice40: Derive PLL timing constraints

- ice40/pcf.cc
Signed-off-by: Tim Callahan <tcal@google.com>
> Use std::string::find(char c) when searching for a single character.

- common/archcheck.cc
This avoids storing the entire pip to wire map in memory with a dramatic memory decrease (2 GB to 200 MB for
A35T), and basically no runtime affect (or slight improvement).
> Use a LRU cache for pip to wire map.

- common/command.cc
- common/nextpnr.h
- frontend/frontend_base.h
This is to decouple the command line flag "--json" and enable other frontend's.
> Add design_loaded state variable.

- .cirrus.yml
- fpga_interchange/arch.cc
- fpga_interchange/arch.h
- fpga_interchange/family.cmake
- fpga_interchange/main.cc
- fpga_interchange/xdc.cc
- fpga_interchange/xdc.h
> Add XDC parser to FPGA interchange

- .cirrus.yml
- docs/generic.md
- generic/arch.cc
- generic/arch.h
- generic/arch_pybindings.cc
- generic/archdefs.h
Also tests support for one cell pin mapping to more than one bel pin in general
> Add bel pin mapping control to nextpnr-generic

- fpga_interchange/arch.cc
- fpga_interchange/arch.h
This also expands the FPGA interchange Arch BBA to include placement constraints, but doesn't implement them yet.
> Add Cell -> BEL Pin maps to FPGA interchange arch.

- generic/pack.cc
Accidental copy-pasta from ice40 was creating an unneeded `GENERIC_SLICE` for Vcc causing issues for things that don't use the slices (like the minimal bel-pin test for example).
> generic: Don't generate Vcc if not needed

- common/command.cc
- common/placer_heap.cc
Expose to users more control over internal parameters.
* For now ice40 only and for the placer heap , but looking forward for more suggestions.
* It is useful for automated annealing see an early experiment: https://github.com/cbalint13/nextpnr-anneal
Thank you !
> Expose ice40 arch placer-heap internal parameters.

- .cirrus/archcheck.sh
- gowin/arch.cc
- gowin/arch.h
This fixes a few recent regressions for gowin and adds archcheck to CI to reduce the likelihood of this happening in the future.
> Gowin regression fixes

- .gitignore
- common/constraints.h
- common/constraints.impl.h
- common/exclusive_state_groups.h
- common/exclusive_state_groups.impl.h
- common/nextpnr.h
- common/util.h
- fpga_interchange/README.md
- fpga_interchange/arch.cc
- fpga_interchange/arch.h
- fpga_interchange/arch_pack_io.cc
- fpga_interchange/examples/archcheck/Makefile
- fpga_interchange/examples/archcheck/test_data.yaml
- fpga_interchange/examples/common.mk
- fpga_interchange/examples/create_bba/Makefile
- fpga_interchange/examples/create_bba/README.md
- fpga_interchange/examples/lut/Makefile
- fpga_interchange/examples/lut/lut.v
- fpga_interchange/examples/lut/lut.xdc
- fpga_interchange/examples/lut/run.tcl
- fpga_interchange/examples/template.mk
- fpga_interchange/examples/wire/Makefile
- fpga_interchange/examples/wire/run.tcl
- fpga_interchange/examples/wire/wire.v
- fpga_interchange/examples/wire/wire.xdc
- fpga_interchange/fpga_interchange.cpp
- fpga_interchange/main.cc
- fpga_interchange/site_router.cc
This PR is too big for review/merge, but it is a WIP branch with a first cut at something that can:
- Read a FPGA interchange logical netlist
- Constrain IO ports via XDC
- Route from an IBUF to an OBUF
- Write a FPGA interchange physical netlist
I have the nextpnr portion of the flow complete, but I need to finish debugging the writing of the physical netlist.  After I get something that works (e.g. can route a wire, etc), I'll need to refactor this PR into smaller portions.
> Complete FPGA interchange Arch to the point where it can route a wire

- common/nextpnr.cc
- common/nextpnr.h
- common/place_common.cc
- common/place_common.h
- common/placer1.cc
- common/placer_heap.cc
Starting by documenting the legalise_placement_strict function a bit better
> Tidying up HeAP

- common/dynamic_bitarray.h
Test PR is over here: https://github.com/YosysHQ/nextpnr-tests/pull/6
> Add dynamic bitarray to common library.

- common/placer1.cc
- common/placer_heap.cc
- common/router1.cc
- common/router2.cc
- common/scope_lock.h
Also check return of placer1_refine.
> Add placement sanity check in placer_heap.

- CMakeLists.txt
This was omitted from PR #617 by mistake, caught on CI.
> Don't include Abseil if it is not used

- common/bits.cc
- common/bits.h
- common/dynamic_bitarray.h
- common/exclusive_state_groups.h
- common/placer1.cc
- common/placer_heap.cc
- common/router1.cc
- common/router2.cc
- common/scope_lock.h
- fpga_interchange/arch.cc
- fpga_interchange/arch.h
- fpga_interchange/luts.cc
- fpga_interchange/luts.h
Needs https://github.com/YosysHQ/nextpnr-tests/pull/7 merged and updated here to build green.
> Use NEXTPNR_NAMESPACE macro's now that headers are seperated.

- .github/ci/build_interchange.sh
- fpga_interchange/arch.cc
- fpga_interchange/arch.h
- fpga_interchange/chipdb.h
PR is based on #635, part 2 of many for breaking up PR #627.
This is relatively small delta from #635, mostly just a chip db schema update and some logic to start using that new pseudo pip data.
> Add pseudo pip data

- fpga_interchange/fpga_interchange.cpp
Local site sources should have their driving BEL pin included in the net
so that the site wire is driven by an output BEL pin.
Also handle cases where a cell pin is missing from the cell -> BEL map.  This is common, but weird.  For now generate a warning.  Improve logic with further iteration.
> Correct some bugs in writing of physical netlist w.r.t. site sources.

- fpga_interchange/arch.cc
- fpga_interchange/arch.h
Also add some optional diagnostic prints for cell -> BEL pin mapping.
> [FPGA interchange] Convert some string constants to IdString.

- .github/ci/build_interchange.sh
- common/dynamic_bitarray.h
- common/property.h
- fpga_interchange/arch.cc
- fpga_interchange/arch.h
- fpga_interchange/cell_parameters.cc
- fpga_interchange/cell_parameters.h
- fpga_interchange/chipdb.h
- fpga_interchange/examples/chipdb.cmake
- fpga_interchange/examples/devices/xc7a35t/CMakeLists.txt
- fpga_interchange/site_arch.h
- fpga_interchange/site_arch.impl.h
- fpga_interchange/site_router.cc
- fpga_interchange/site_routing_cache.cc
- fpga_interchange/site_routing_cache.h
This builds on #640, and is the last PR from #627.
> [FPGA interchange] Add support for global buffers from chipdb.

- nexus/pdc.cc
> nexus: Add support for get_pins PDC command

- .github/ci/build_interchange.sh
- .github/workflows/interchange_ci.yml
- fpga_interchange/examples/chipdb.cmake
> interchange: add archcheck tests to all-device-test target

- fpga_interchange/arch.cc
Previous code allowed router to enter sites with no sinks.
> [interchange] Fix site pip check for drivers.

- .github/ci/build_interchange.sh
- .github/workflows/interchange_ci.yml
- fpga_interchange/arch.cc
- fpga_interchange/chipdb.h
- fpga_interchange/luts.h
Changes:
- Adds LUT output pin to LutBelPOD.
> [interchange] Update to v6 of FPGA interchange chipdb.

- common/router2.cc
Was introduced in #612.  The logic before was intended to prevent the
router from terminating early when not using a bounding box, but the fix
in #612 simply removed that, meaning that the router might terminate
early incorrectly.  The solution here is to only use the toexplore
hysteric once a solution is found.
> Fix bug in router2 where router may give up too early.

- .github/workflows/interchange_ci.yml
- common/router2.cc
- fpga_interchange/arch.cc
- fpga_interchange/arch.h
- fpga_interchange/luts.cc
- fpga_interchange/luts.h
- fpga_interchange/pseudo_pip_model.cc
- fpga_interchange/pseudo_pip_model.h
- fpga_interchange/site_arch.cc
- fpga_interchange/site_arch.h
- fpga_interchange/site_arch.impl.h
- fpga_interchange/site_router.cc
Builds on #658.  @gatecat May break this PR further if you'd like.
> [interchange] Pseudo pip fixes

- fpga_interchange/arch.cc
The pins created for tieing to Vcc were being named after the bel pin, relying on the fact that Xilinx names cell and bel pins differently for LUTs. This isn't true for Nexus devices which uses the same names for both, and was causing a failure as a result.
This uses a "PHYS_" prefix that's highly unlikely to appear in a cell pin name to disambiguate.
cc @litghost
> interchange: Disambiguate cell and bel pins when creating Vcc ties

- common/fast_bels.h
@adamgreig, does this look like a reasonable solution to #672  ?
> fast_bels: Don't return pointer that might become invalid

- common/timing.cc
- common/timing.h
> timing: Fix domain init when loops are present

- fpga_interchange/pseudo_pip_model.cc
These are used for the LUT-as-GND-driver pseudo-pips in the Nexus arch, which will probably be required for UltraScale too.
Anyone want to give this a review? @acomodi or @tmichalak ?
> interchange: Allow pseudo-cells with no input pins

- common/arch_pybindings_shared.h
- fpga_interchange/arch_pybindings.cc
> Add Python bindings for placement tests

- .github/workflows/interchange_ci.yml
- fpga_interchange/arch.cc
- fpga_interchange/arch.h
- fpga_interchange/chipdb.h
- fpga_interchange/fpga_interchange.cpp
see also SymbiFlow/python-fpga-interchange#65
> interchange: Handle missing/disconnected cell pins

- fpga_interchange/arch_pack_io.cc
Signed-off-by: Jan Kowalewski <jkowalewski@antmicro.com>
> interchange: allow LOC keyword in XDC files

- nexus/arch.cc
Although not a total fix, this seems to improve some failures to route
> nexus: Enable placeAllAtOnce

- .github/workflows/interchange_ci.yml
- common/arch_pybindings_shared.h
- fpga_interchange/arch.cc
- fpga_interchange/chipdb.h
See SymbiFlow/python-fpga-interchange#77
> interchange: Add wire types

- common/router2.cc
Also, use the net bounding box rather than the arc bounding box to encourage more resource re-use. This might still need some more tweaks, but it is hopefully a not-worsening overall.
> router2: Dynamicly expand bounding box based on congestion

- common/router2.cc
These are part of my planning for some much faster data structures during routing in the medium-term future.
> router2: Add some boundness statistics

- .github/workflows/interchange_ci.yml
Needed to test subtile FASM generation
> interchange: Bump versions

- .github/ci/build_interchange.sh
- .github/workflows/interchange_ci.yml
- fpga_interchange/examples/boards/CMakeLists.txt
- fpga_interchange/examples/devices/CMakeLists.txt
- fpga_interchange/examples/devices/LIFCL-40/CMakeLists.txt
- fpga_interchange/examples/devices/LIFCL-40/test_data.yaml
- fpga_interchange/examples/tests/counter/CMakeLists.txt
- fpga_interchange/examples/tests/counter/lifcl40evn.xdc
- fpga_interchange/examples/tests/lut_nexus/CMakeLists.txt
- fpga_interchange/examples/tests/wire/CMakeLists.txt
- fpga_interchange/examples/tests/wire/lifcl40evn.xdc
- fpga_interchange/examples/tests/wire/run_nexus.tcl
This will be important for testing FASM generation.
> interchange: Add LIFCL-40 EVN tests

- .github/ci/build_mistral.sh
- .github/workflows/mistral_ci.yml
- CMakeLists.txt
- mistral/arch.cc
- mistral/arch.h
- mistral/family.cmake
- mistral/main.cc
See Ravenslofty/mistral#13
We also need to look at better versioning long term, probably managing the mistral clone in CMake, but that's for another PR.
> Updates for latest libmistral

- common/command.cc
- common/command.h
- gui/basewindow.cc
> gui: Don't destroy context when loading JSON

- fpga_interchange/dedicated_interconnect.cc
> interchange: Handle disconnected bel pins in dedicated interconnect

- fpga_interchange/arch.cc
- fpga_interchange/site_arch.h
- fpga_interchange/site_router.cc
- fpga_interchange/site_routing_cache.cc
- fpga_interchange/site_routing_cache.h
Fixes #740, with this patch the "wire" test is now working on ZCU104 hardware
cc @acomodi
> interchange: Reserve site ports only reachable from dedicated routing

- fpga_interchange/site_router.cc
This is required because UltraScale+ inversion bels don't have separate inverting and non-inverting inputs like on xc7, but rather a single 'can invert' input.
With this patch, a basic counter example is working on my ZCU104 UltraScale+ hardware using a button as a clock input with dedicated clock buffers disabled due to a couple of remaining issues there.
> interchange: Handle canInvert PIPs when processing preferred constants

- machxo2/arch.h
- machxo2/bitstream.cc
- machxo2/cells.cc
- machxo2/cells.h
- machxo2/examples/README.md
- machxo2/examples/demo-vhdl.sh
- machxo2/examples/prims.vhd
- machxo2/examples/tinyfpga.vhd
- machxo2/pack.cc
I've made enough bug fixes that didn't get caught during the initial PR that it's worth making another PR to fix them. Fixes include initial VHDL support, generating global routing connections (global routing still unsupported), and fixing packing FFs that do not have LUTs attached to their inputs.
> MachXO2 Checkpoint 1

- fpga_interchange/fpga_interchange.cpp
It seems that https://github.com/YosysHQ/nextpnr/pull/742 let the physical netlist writer ignore nets that should be actually present in the physical netlist as they are present in the logical netlist as well.
This PR lets the frontend netlist reader mark nets that are bound to disconnected ports (thus not present in the logical netlist) that can be later recognized when writing the physical netlist and ignored.
> interchange: phys: skip only nets writing on disconnected out ports

- common/design_utils.cc
> design_utils: Fix memory error

- common/timing.cc
> timing: Fix out-of-bounds histogram bins in all cases

- gowin/main.cc
Fixes https://github.com/YosysHQ/nextpnr/pull/751#pullrequestreview-703577706
> GW1NR is not a seperate family, but GW1NS is

- .github/workflows/interchange_ci.yml
- fpga_interchange/chipdb.h
> [interchange] Update chipdb and python-fpga-interchange versions

- fpga_interchange/arch.cc
This solves the failing tests in https://github.com/SymbiFlow/fpga-interchange-tests/pull/45
> interchange: disallow pseudo-pip on same nets if tile has luts

- fpga_interchange/arch_pack_io.cc
This gets `IBUFDS` and `IOBUFDS` placement working on xc7 where both P & N sides must be placed for the sites to become valid. It also adds a check to prevent the IO placer ever ripping up bels that are already placed.
DRC passes and bitstreams generate OK, I haven't tested on hardware as I don't think I have a basys3 lying around - cc @mkurc-ant 
Fixes #774
> interchange: Check IO validity after all are placed

- fpga_interchange/arch_pack_io.cc
This is needed for ensuring the inverters in a pseudo-differential IO are placed at the correct, dedicated, sites, rather than at a random LUT which won't be reachable from an OSERDES.
> interchange: Search backwards for IO macro placements, too

- common/router2.cc
Previously, the route delay updates did nothing because routes aren't bound while any congestion at all is present. This instead uses our calculations based on the router2-internal binding state to update route delays at every iteration.
> router2: Update route delays even when routes are congested

- common/router2.cc
- nexus/global.cc
> nexus: Fix routeing of global clocks that also drive fabric

- ecp5/pack.cc
> ecp5: Copy REGMODE in PDP mode to both A and B ports

- ecp5/pack.cc
Avoids a segfault if an EXTREFB does not connect directly to its associated DCUA.
Also adds location constraints specifically for EXTREFB.
> Make EXTREFB handling more robust

- common/arch_pybindings_shared.h
- python/delay_vs_fanout.py
> python: Allow querying route delays

- gowin/arch.cc
Specifying pin placement with this notation (e.g. IOR4B) allows
to use the same constraint file without changes for different
packages and even different families.
The vendor router also understands this notation.
> gowin: Add the IO[TRBL]style placement recognition

- fpga_interchange/xdc.cc
> interchange: xdc: add more not_implemented commands

- common/command.cc
- common/command.h
> command: Allow running Python on failure for state introspection

- common/placer1.cc
This needs a bit more testing, but it fixes a bit of a long-stuck barnacle that placer1 (importantly, used by HeAP for refinement) wouldn't swap anything relatively constrained with anything else relatively constrained. For arches that rely a lot on relative constraints (for example, every WIDEFN9 in Nexus is two relatively constrained LUT4s), this would hurt QoR a bit.
> placer1: Allow swapping chains with other chains

- nexus/arch.cc
- nexus/arch.h
> nexus: Tweaks for router1 performance

- common/pybindings.cc
Several times when running `interactive.py` to debug nextpnr state, I've hit Ctrl+C assuming I was in a typical Python session and lost state because the standard Python SIGINT handler is disabled. This PR re-enables it while running Python only.
> python: Restore SIGINT handler while running a Python script

- nexus/arch.cc
- nexus/constids.inc
- nexus/fasm.cc
nextpnr side changes to support gatecat/prjoxide#15
> nexus: Support for split Vcc routing

- common/placer1.cc
Issue was due to dest_bels being not cleared between clusters unbindes, causing
newly bind bels to be unbinded and having their old bel value changed to new bel value.
Then when swap failed 2 cells were being bind to a single bel.
I tested leaving dest_bels in the function scope and moving it to the loop scope.
Code with dest_bels in the loop scope was faster than leaving it in the function scope,
and checking if the cell is in the processed cluster.
> Fix chain swap

- ecp5/pack.cc
> Fix mistype.

- fpga_interchange/arch_pack_clusters.cc
> interchange: fix uninitialized memory bug in cluster placement

- common/log.cc
based on https://github.com/YosysHQ/yosys/commit/c5e9034834ce0bcc6f6c611bc3ad3d244a32732f#diff-3ea18389616e5c64fa0a5cda797bfb4223f6881cf04540d59622a22feae4010fR169
> Fix Cygwin build

- mistral/arch.cc
No functional change, but a little prettier.
> mistral: clean up bel init slightly

- gowin/arch.cc
- gowin/cells.cc
- gowin/constids.inc
gowin: Replace the zero delays with reasonable values.
> gowin: Replace the zero delays with reasonable values.

- common/router2.cc
- mistral/arch.cc
- mistral/arch.h
- mistral/delay.cc
Featuring hardcoded timing information, yay :P
> mistral: very basic timing info

- ecp5/cells.h
- ecp5/pack.cc
> ecp5: Fix packing of IOFF with IODELAYs

- gowin/pack.cc
> gowin: BUGFIX. Place the ALU head in sliсe 0 only

- gowin/arch.cc
> gowin: Fix spelling of messages

- frontend/frontend_base.h
> frontend: Consider net aliases when uniquifying name

- common/router1.cc
This uses criticality to weight penalties; so critical arcs are encouraged to rip up potentially less critical ones
> router1: Improve timing heuristic

- common/command.cc
- common/router1.cc
- common/router2.cc
> router1: Experimental timing-driven ripup support

- .github/workflows/mistral_ci.yml
- mistral/bitstream.cc
> mistral: Update to latest enum name

- ice40/pack.cc
> ice40: Pack LUT at start of carry chain if there is 1 candidate

- nexus/pack.cc
In the previous PR https://github.com/YosysHQ/nextpnr/pull/900 for this feature constraints were adjusted in the wrong direction. This one fixes that
> Honor nexus OSCA frequency tolerance (corrected)

- nexus/arch.cc
> nexus: Hotfix to disable unimplemented DCS routethru

- generic/viaduct_helpers.cc
- generic/viaduct_helpers.h
> viaduct: Allow constraining only cascades without fanout

- docs/archapi.md
Fixed formatting typo in archapi.md
> Fixed formatting typo in archapi.md

- common/idstringlist.h
> Add IdStringList::concat overrides taking IdString

- ecp5/pack.cc
> ecp5: Fix PDPW16K clock param renaming

- gowin/arch.cc
> gowin: BUGFIX gui crash

- common/placer_heap.cc
Not sure how I missed this before, sorry.
> Add missing part of PR #933

- ice40/pack.cc
nextpnr-ice40 was crashing when packing forcefully placed LUTs with no output
The same error is probably in the generic packer at https://github.com/YosysHQ/nextpnr/blob/master/generic/pack.cc#L50
But I didn't have the setup to test it.
MWE:
run the following command to checkout the bug: 
`nextpnr-ice40 --up5k --package sg48 -v --json test.json.txt --pcf icoboard.pcf.txt`
[test.json.txt](https://github.com/YosysHQ/nextpnr/files/8244420/test.json.txt)
[icoboard.pcf.txt](https://github.com/YosysHQ/nextpnr/files/8244426/icoboard.pcf.txt)
> ice40: fix crash when packing LUTs with no output

- gowin/main.cc
> gowin: don't crash if no arguments are set

- .github/ci/build_interchange.sh
- .github/workflows/interchange_ci.yml
> ci: Fixes for latest RapidWright

- .github/workflows/mistral_ci.yml
- mistral/bitstream.cc
> mistral: Update to latest upstream

- .github/workflows/mistral_ci.yml
- mistral/bitstream.cc
> mistral: Updated CLK mux select name

- .cirrus/Dockerfile.ubuntu20.04
- ecp5/arch.cc
- ecp5/arch.h
- ecp5/arch_place.cc
- ecp5/archdefs.h
- ecp5/bitstream.cc
- ecp5/cells.cc
- ecp5/cells.h
- ecp5/constids.inc
- ecp5/gfx.cc
- ecp5/globals.cc
- ecp5/pack.cc
- ecp5/trellis_import.py
This is one of those big scary PRs as far as the size of the change goes! :D
There are still some possible small QoR and runtime regressions with this that are being worked on, although most designs should not be significantly worse; and importantly some high utilisations designs that were previously failing to fit or route now build successfully.
This also helps align things better with the future direction of nextpnr and clears up some barnacles.
> ecp5: Split the SLICE bel into separate LUT/FF/RAMW bels

- common/place/detail_place_core.cc
- common/place/parallel_refine.cc
> prefine: Do full-tile swaps, too

- generic/arch.cc
- generic/arch.h
- generic/viaduct_helpers.cc
- generic/viaduct_helpers.h
> generic: Add some extra helpers for viaduct uarches

- gowin/arch.cc
Only the recognition of the directive in the .CST file and elementary
checks are added, but not the long-wire mechanism itself.
> gowin: Add initial syntax support for long wires

- ice40/pack.cc
> ice40: Fix propagation of constraints through SB_GB

- common/kernel/nextpnr_types.cc
> common: Correct a minor typo in the message

- nexus/fasm.cc
> Change write_dcc to work with tilegroups from prjoxide

- gowin/arch.cc
In the Gowin chips, the tiles are connected to each other by a one-hop
wire, among others. There are 4 one-hop wires, of which 2 are shared
between north/south and east/west, have three names: e.g. SN10 and N110
and S110.
But only one of them, the first, occurs as a sink for PIP, that is, you
can not get a route that would pass through the S110 for example.
This commit corrects the names to SN?0 and EW?0 at the wire creation
stage to avoid dead wires.
In addition, the SN?0 and EW?0 are among the few sinks for global clock
wires and now there is the possibility of a more optimal clock routing.
> gowin: Use local aliases

- generic/arch.cc
- generic/arch.h
- generic/arch_pybindings.cc
> generic: addBelPin with direction as an arg

- common/kernel/basectx.cc
- common/kernel/basectx.h
- common/kernel/nextpnr_types.cc
- ecp5/arch.cc
- ecp5/pack.cc
- fpga_interchange/arch.cc
- fpga_interchange/macros.cc
- generic/viaduct/example/example.cc
- generic/viaduct/okami/okami.cc
- generic/viaduct_helpers.cc
- gowin/pack.cc
- ice40/arch.cc
- machxo2/arch.cc
- mistral/arch.cc
- mistral/globals.cc
- mistral/io.cc
- mistral/lab.cc
- mistral/m10k.cc
- mistral/pack.cc
- nexus/arch.cc
- nexus/fasm.cc
- nexus/pack.cc
> refactor: id(stringf(...)) to new idf(...) helper

- ecp5/arch.cc
- ecp5/arch.h
- ecp5/arch_place.cc
- ecp5/bitstream.cc
- ecp5/cells.cc
- ecp5/cells.h
- ecp5/gfx.cc
- ecp5/globals.cc
- ecp5/pack.cc
- gowin/cells.cc
- gowin/gfx.cc
- gowin/globals.cc
- ice40/arch.cc
- ice40/arch_place.cc
- ice40/bitstream.cc
- ice40/cells.cc
- ice40/cells.h
- ice40/pack.cc
- mistral/globals.cc
- nexus/arch.cc
- nexus/arch.h
- nexus/fasm.cc
- nexus/global.cc
- nexus/pack.cc
> refactor: Use IdString::in instead of || chains

- generic/main.cc
> viaduct: Allow passing command line options to uarch with -o

- nexus/arch.cc
- nexus/arch.h
- nexus/main.cc
> nexus: Add ES2 device names and --list-devices

- ice40/bitstream.cc
Fixes #910, using the patch from @jswrightoc
> ice40: Fix UltraPlus BRAM clock polarity

- ecp5/bitstream.cc
This makes the bitstream generation a tiny bit tidier, also taking 10-20 seconds off rebuilds.
> ecp5: Split bitstream generation into more functions

- common/kernel/timing.cc
disable null pointer dereference!
> Fix runtime segmentation fault

- ice40/bitstream.cc
> ice40: Fix handling of carry out route-thru via 25,14

- ecp5/arch_pybindings.cc
Thanks to @Ravenslofty for finding this one!
> ecp5: Fix Python bindings for pip iterators

- .github/workflows/arch_ci.yml
- common/kernel/arch_api.h
- common/kernel/base_arch.h
- docs/archapi.md
- ecp5/arch.h
- fpga_interchange/arch.cc
- fpga_interchange/arch.h
- generic/arch.cc
- generic/arch.h
- generic/viaduct_api.h
- ice40/arch.h
- mistral/arch.h
- nexus/arch.h
> api: Make NetInfo* of checkPipAvailForNet const

- generic/viaduct_helpers.cc
> viaduct: Fix constant connectivity

- common/kernel/arch_api.h
- common/kernel/base_arch.h
- common/kernel/nextpnr_base_types.h
- common/place/placer_heap.cc
- common/route/router2.cc
- docs/archapi.md
- ecp5/arch.cc
- ecp5/arch.h
- fpga_interchange/arch.cc
- fpga_interchange/arch.h
- fpga_interchange/arch_pack_clusters.cc
- fpga_interchange/cost_map.cc
- fpga_interchange/cost_map.h
- generic/arch.cc
- generic/arch.h
- generic/viaduct_api.cc
- generic/viaduct_api.h
- gowin/arch.cc
- gowin/arch.h
- ice40/arch.cc
- ice40/arch.h
- machxo2/arch.cc
- machxo2/arch.h
- mistral/arch.cc
- mistral/arch.h
- nexus/arch.cc
- nexus/arch.h
This can actually be a more generic bounding box type than the name suggests.
> refactor: rename ArcBounds -> BoundingBox and use this in HeAP

- common/kernel/arch_api.h
- common/kernel/arch_pybindings_shared.h
- common/kernel/base_arch.h
- common/place/placer1.cc
- common/place/placer_heap.cc
- docs/archapi.md
- docs/viaduct.md
- ecp5/arch.h
- ecp5/arch_place.cc
- fpga_interchange/arch.h
- generic/arch.cc
- generic/arch.h
- generic/viaduct/example/example.cc
- generic/viaduct/fabulous/fabulous.cc
- generic/viaduct/okami/okami.cc
- generic/viaduct_api.h
- gowin/arch.cc
- gowin/arch.h
- ice40/arch.h
- ice40/arch_place.cc
- machxo2/arch.cc
- machxo2/arch.h
- mistral/arch.cc
- mistral/arch.h
- nexus/arch.h
- nexus/arch_place.cc
> Add new option for verbose validity errors, use for ice40

- gowin/gfx.cc
As preparation for possible changes to the clock wiring system.
> gowin: not crush on unknown clock tap's sources

- common/place/placer_heap.cc
Include all cell types in chain size calculation
> heap: encourage more spreading of heterogenous chains

- docs/netlist.md
> doc: fix a mistype

- ecp5/lpf.cc
> ecp5: Improve error handling for missing end-"

- ecp5/pack.cc
> ecp5: Improve IOFF CE handling robustness

- ecp5/lpf.cc
Fixes https://github.com/YosysHQ/nextpnr/issues/1036
Not really that important. But it was easy to fix and gets myself started with nextpnr dev workflow!
> ecp5: LOCATE in LPF works on singleton vector

- ecp5/pack.cc
> ecp5: Handle the case where both CE are the same constant

- generic/viaduct/fabulous/fabric_parsing.h
- generic/viaduct/fabulous/fabulous.cc
> fabulous: Improve names for BRAM bels

- common/kernel/command.cc
- common/kernel/log.cc
- common/kernel/log.h
Fixes https://github.com/YosysHQ/nextpnr/issues/498
> common: Implement Werror flag

- generic/arch.h
- generic/viaduct/fabulous/fabulous.cc
These are not intended to be realistic, but without them nextpnr won't perform any timing optimisations.
> fabulous: Add fake timings

- common/kernel/constraints.impl.h
- common/kernel/exclusive_state_groups.h
- common/kernel/exclusive_state_groups.impl.h
See https://en.cppreference.com/w/cpp/language/requires for more details.
>  rename c++20 keyword s/requires/requires_range.

- common/kernel/timing.cc
Fixes https://github.com/YosysHQ/nextpnr/issues/1158
> Fix segfault when clocking a FF from a ring oscillator

- mistral/pack.cc
The 13x1-bit M10K mode was always a bit strange in how it worked. That lead to some breakage when it came to edge cases:
- because the data pins are single-bit, they don't have indexing in their names, which meant that bel pin lookup crashed because the code assigned to `[AB]1DATA[0]` but the lookup was for `[AB]1DATA`.
- the `bit_offset` lead to the address bel pins being off-by-one, causing another crash due to there being no `ADDRB[12]`.
Thanks to @infphyny for reporting in olofk/fusesoc#552.
> mistral: fix corner cases related to 13x1-bit M10Ks

- common/kernel/timing.cc
- common/kernel/timing.h
Required to get reports working for async paths in https://github.com/YosysHQ/nextpnr/pull/1149
> Analyse async paths in TimingAnalyser

- common/kernel/timing.cc
Fixes https://github.com/YosysHQ/nextpnr/issues/1174
> Timing: Fix combinational paths through all ports

- machxo2/pack.cc
> Widelut support for Mach XO2/XO3/XO3D

- ecp5/pack.cc
> ecp5: Improve packer robustness to FF dangling M input

- himbaechel/himbaechel_dbgen/chip.py
@yrabbit can you confirm this is enough to make it work for you?
> himbaechel: Fix for Python 3.9

- common/kernel/command.cc
We add support right here so that later I don’t have to make patches to the ports.
> gowin: Himbaechel. Support DragonFlyBSD

- 3rdparty/oourafft/fftsg.cc
- 3rdparty/oourafft/fftsg.h
- 3rdparty/oourafft/fftsg2d.cc
- 3rdparty/oourafft/readme.txt
- 3rdparty/oourafft/readme2d.txt
- CMakeLists.txt
- common/kernel/array2d.h
- common/kernel/deterministic_rng.h
- common/place/placer_static.cc
- common/place/placer_static.h
- common/place/static_util.h
- ecp5/arch.cc
This is not yet at a point where it will bring benefits for real-world designs, but it is now a complete and working placer flow including a legaliser.
The primary remaining issue is that we aren't doing enough to prepare the placement for legalisation (like converging carry chains, dealing with control set issues, etc etc) which means there's a big jump in wirelength and so degrade in QoL at this point that the detail placer than has to try and deal with (but isn't designed for).
Other issues are that the heuristics for adjusting penalties etc are currently very crude, and it is likely that in some cases the solver just won't converge. There is also scope for multithreading in lots of places (perhaps with OpenMP), although runtime isn't that bad. The FFTs do mean there is a relatively …
> placer_static: Initial prototype

- himbaechel/uarch/gowin/pack.cc
Fixed incorrect use of attributes instead of parameters.
> gowin: Himbaechel. Diff io BUGFIX.

- gowin/pack.cc
- himbaechel/uarch/gowin/globals.cc
- himbaechel/uarch/gowin/pack.cc
What compiler found, only for gowin. %zu for size_t and PRIX64 for int64_t in hexadecimal
> Fix printf formats

- himbaechel/himbaechel_dbgen/chip.py
Himbächel was always intended to support up to 2³² unique node shapes, hence it being split across two words, but as the multi-purpose structure was being encoded as signed shorts, this would fail in the lower part as soon as 32768 were exceeded.
> himbaechel: Fix when more then 32k unique node shapes

- gui/fpgaviewwidget.cc
- gui/line_editor.cc
At least display proper grid for each platform in GUI (including Himbaechel).
Also added compile warning fix in GUI related code
> GUI fix when no decals are defined

- himbaechel/uarch/gowin/globals.cc
Ignore networks without users.
Addressed https://github.com/YosysHQ/apicula/issues/232
> gowin: Himbaechel. Global router BUGFIX.

- himbaechel/uarch/gowin/globals.cc
A small improvement - do not waste time analyzing already processed networks in the previous step (and possibly steps).
> gowin: Himbaechel. Improve the global router

- .github/ci/build_himbaechel.sh
- .gitignore
- gui/fpgaviewwidget.h
- gui/lineshader.h
- himbaechel/uarch/example/CMakeLists.txt
- himbaechel/uarch/example/example.cc
- himbaechel/uarch/example/example_arch_gen.py
These are cherry-picked commits from https://github.com/YosysHQ/nextpnr/pull/1295 that fix some QT related warnings/issues and makes Example uarch from himbaechel to behave more like other architectures.
> QT related and Example uarch cleanup

- common/kernel/command.cc
- common/kernel/context.h
- common/kernel/sdc.cc
The coming 2 months I have a lot of time to work on nextpnr. I want to make the timing changes I make to be small so I will make small PRs to get them merged asap. 
First step is to get SDC support merged with clock frequency support.
> SDC parsing support

- ecp5/globals.cc
- ecp5/main.cc
Closes https://github.com/YosysHQ/nextpnr/issues/1043
And more easily allows me to continue working on clock skew analysis.
> ecp5: Allow disabling of global promotion

- common/place/placer_static.cc
I guess this should be a `std::min`.
> Placer: Fix static legalise radius

- himbaechel/uarch/gowin/globals.cc
Adds additional restrictions on the first PIP after the clock source - only connections to SPINEs are allowed. This allowed to correct the behaviour of DQCEs since the latter can only disable/enable SPINEs.
Fixes #1408
> Gowin. BUGFIX. Global clock routing.

- ice40/pack.cc
When constraining LCs to the tile giving them PLL lock output access, don't pack more than one flipflop-containing LCs as they might be incompatible. Fixes #1406
> ice40: Don't constrain multiple potentially-incompatible FFs to same tile

- cmake/BBAsm.cmake
> CMake: fix windows BBA resource embedding

- .github/ci/build_rust.sh
- .github/workflows/arch_ci.yml
This is a guard against bitrot, and also probably useful given that I intend to bind more nextpnr APIs in the future.
> ci: test that BUILD_RUST=ON builds

- rust/nextpnr/src/lib.rs
- rust/rust.cc
(at what point do I spend the time trying to figure out a pattern for passing these iterators between C++ and Rust that doesn't require leaking an array?)
> rust: add getBels() binding

- himbaechel/uarch/gatemate/gatemate_util.h
- himbaechel/uarch/gatemate/pack.cc
Updated based on some explanations and new test cases.
All routeing data already available in chip database
> gatemate: implemented remaining PLL features

- himbaechel/uarch/gatemate/route_clock.cc
Follow-up PR to #1483, which resolves the bug mentioned in that thread.
(Now to debug router2...)
> Reserve sinks in GateMate clock router

- himbaechel/uarch/gatemate/pack_clocking.cc
Solves priority issue when placing BUFG for PLL, some ports have one option but other have two routing options, needs to be checked in order to satisfy routing.
> gatemate: PLL priority for BUFG

- himbaechel/uarch/gatemate/route_clock.cc
Sometimes the clock router ends up accidentally using signals for non-global clocks; as a brute-force solution, we reserve every CPE with a clock to avoid this.
> Reserve all CPE control signals in clock router

- himbaechel/uarch/gatemate/route_clock.cc
Minimising clock skew is so vital to avoiding hold violations that even in situations where there are too many clocks to assign to clock buffers, it's still worth it to use the clock router.
> Use clock router even for non-global clocks

- himbaechel/uarch/gowin/globals.cc
Use loop enumeration of PIPs instead of direct name construction for the upper and lower ends of the segment wire.
Also do not allow clock wires for segments.
> Gowin. Unbreak the segment routing.

- himbaechel/uarch/gatemate/CMakeLists.txt
- himbaechel/uarch/gatemate/bitstream.cc
- himbaechel/uarch/gatemate/gatemate.h
- himbaechel/uarch/gatemate/pack.cc
- himbaechel/uarch/gatemate/pack.h
- himbaechel/uarch/gatemate/pack_mult.cc
Merge initial multiplier support into gatemate branch
> Multiplier support

- ecp5/pack.cc
> ecp5: Fix placement of ECLKSYNCB driving PLL CLKFB

- himbaechel/uarch/gatemate/bitstream.cc
- himbaechel/uarch/gatemate/cells.cc
- himbaechel/uarch/gatemate/constids.inc
- himbaechel/uarch/gatemate/gen/arch_gen.py
- himbaechel/uarch/gatemate/pack_clocking.cc
- himbaechel/uarch/gatemate/pack_io.cc
Separate IO selection from rest of GPIO, to simplify code
> gatemate: add IOSEL as separate primitive

- himbaechel/uarch/gatemate/pack_cpe.cc
Does not change anything on bitstream level, but helps with netlist.
> gatemate: special case RAMIO when needed

- common/route/router2.cc
When using CPE Bridge Mode in the gatemate uarch (upcoming PR), there can be routing conflicts between logic inside the CPE, and the router using the bridge through an output. Because there are several muxes to navigate between the logic output and the general routing, we iteratively reserve arc drivers until routing is reached to avoid these conflicts.
> router2: iteratively reserve arc driver wires, too

- common/place/placer_heap.cc
- himbaechel/uarch/gatemate/gatemate.cc
- himbaechel/uarch/gatemate/gatemate.h
- himbaechel/uarch/gatemate/pack_clocking.cc
This one also runs clangformat that is why placer_heap is affected
> gatemate: code cleanup and netlist fix

- rust/example_printnets/src/lib.rs
- rust/nextpnr/src/lib.rs
- rust/rust.cc
Yes, this is another leaking API. The alternative is trying to implement hashlib in Rust, and I'm not really sure I feel like that right now.
> rust: rework ownership model

- common/place/placer_heap.cc
With current code it was not able to place some of designs, and was constantly trying location out of region box, with this in place it is able to do so.
There could be better way to do it, but this is what came to my mind
> placer_heap: fix clamping to region
